### ISSUE TITLE
Screenshot on the site

### ISSUE THREAD

**Issue by TheJaredWilcurt** [prose/prose#1005]
All I ask is that you show a screenshot of what you're offering before you ask for access to my repos and GitHub account.

Who are you? What are you offering? Is this something I would even use?

All of this is answered in one screenshot.

**Comment by phy25** [comment]
I don't think this make sense. If you don't understand the text `Prose is a content editor for GitHub designed for managing websites.`, you won't know more by a screenshot of the editor.

Rather it's better to add hints like "We need access to your GitHub to identify you and let you modify files in your repos".

**Comment by TheJaredWilcurt** [comment]
I ain't givin' you access if you don't **show** me what you are.

I can already edit files directly on GitHub. Why the hell would I use this?

You need to **show** a value proposition.

I can either:

A. Use the well designed, built in system to do what you are offering, or
B. Give you write access to my repos in order to see *what's in the mystery box!*

Yeah, no. **Show** me what this is, cuz I have no reason to trust it.

**Comment by phy25** [comment]
Sense of secure, huh? I don't think that makes sense. Maybe we have to wait for the third person to say something.

![prose-ss-mockup](https://cloud.githubusercontent.com/assets/331403/20639235/93630c9a-b3f8-11e6-8a83-2671beb21e2d.png)

**Comment by dereklieu** [comment]
You can access the UI without authenticating by going to prose.io/#/:OWNER/:REPO_NAME, for example [http://prose.io/#/prose/prose](http://prose.io/#/prose/prose). You can even open a file and start editing. Of course, you can't commit the edit, but you can get a pretty good idea of what it does.

Furthermore, the entire source code is here for you to audit.

**Comment by TheJaredWilcurt** [comment]
...I don't think you are understanding the point of a screenshot.

It tells me everything I need to know in under a second.

Why would you think reading the entirety of your source code would be desirable over that?

I don't want to build your shit, I just want to see if it's worth using.

If you don't want to do screenshots, and instead want to link to that demo; *fine*, but you **AREN'T** currently. The only way to see anything related to the thing you are trying to get people to use is force them to either give up write access to their repos, or to come to GitHub and file an Issue so someone will link them to the demo.

Does that sound like a ***good*** user experience?

**Comment by dereklieu** [comment]
@TheJaredWilcurt, your attitude comes off as very negative. I don't think that's helping your cause here. Prose is free to use, and is maintained by people who aren't paid for it. Aggressively asking for a feature is not a good way to convince people to do it.

But, point taken, Prose could use a 'What does this do' page. If you'd like to contribute that, I would love to accept a pull request.
