### ISSUE TITLE
Stop wrapping of images in p tags

### ISSUE THREAD

**Issue by wesort** [prose/prose#1012]
By default, images are wrapped in a `p` tag when they are parsed by Jekyll on GH Pages (ref of [issue on Jekyll](https://github.com/jekyll/jekyll-help/issues/188), [ref of issue on Kramdown](https://github.com/gettalong/kramdown/issues/98)). This is a problem if CSS includes any spacing or width styling on the `p` tag. For example, I often add ` p { max-width: 45rem }` to avoid unreadable line-lengths.

To avoid this, there are two workarounds for use in markdown / Prose that I am familiar with (without resorting to javascript).
1. On the line immediately after the img tag, add `{: .image-wrap}`. This will add the `.image-wrap` class to the surrounding `p` tag.
2. Wrap the md img line in a `div`

Perhaps Prose could allow a config setting to automate either one of these workarounds? ie: append a new line with `{: .image-wrap}` after inserting an image.

**Comment by dereklieu** [comment]
Hey @wesort I'm not opposed to the `{: .image-wrap}` idea but am slightly hesitant about inserting class names into other peoples' markup. If anything it'd have to be `.prose--image-wrap` or similarly namespaced.

Perhaps you could solve this on your end by applying the `max-width` style and other relevant styles to the container holding the `<p>` tags rather than the tags themselves. 

I'm also not sure if Prose is actively making this decision; likely it's being delegated to `js-yaml` [github](https://github.com/nodeca/js-yaml), in which case we might not have an option.

**Comment by wesort** [comment]
I would much rather solve it at my end, but until CSS get parent selectors I'm not sure how I would target only the `<p>` tags with `<img>` tags as children?? I cannot apply the `max-width` to the container as that continues the same issue of a container around the image limiting its width.

You are right that GH Pages / Jekyll will be add adding the `<p>` around the images (if that's what you mean?) during the markdown parsing. 

I understand not wanting to insert anything into unsuspecting users. However, my suggestion, to be clear, is for a config option where a user could specify a string to be appended on the next line following the insertion of an image from the WYSIWYG toolbar. Whether that string is `{: .image-wrap}` or `{: .prose--image-wrap}` is somewhat moot right? Obviously I can instruct my users to do this when adding images, but it occurred to me that I might not be an isolated situation.

**Comment by dereklieu** [comment]
Hi @wesort, I totally understand what you're saying. If you need some way to target images for styling, which is what I presume you will be doing with this class, could you instead do something like:

```(css)
.jekyll--content > p { max-width: 45px; }
.jekyll--content > p > img { /* whatever overrides you need */ }
```

Open to discussing further if this ^ doesn't fit your needs.

**Comment by wesort** [comment]
Hi @dereklieu - Thanks and I'd love to target it by CSS but what you suggest doesn't work as [CSS doesn't have parent selector](https://css-tricks.com/parent-selectors-in-css/)s (yet). 

`p > img` will target the img, but the `img` is already being constrained by a max-width on the `p` that is wrapped around it through markdown parsing. Unless I'm missing something, at some point if I want to limit my line length on my `p` tags for readability, I need to add a class to either the `p` or the `p` containing an `img`??

**Comment by dereklieu** [comment]
I understand where you're coming from. I should point out that `max-width` does not size-constrain a child `img` tag unless it's set to a relative width, or the container is set to `overflow: hidden`.

https://codepen.io/anon/pen/MJNQvj

**Comment by wesort** [comment]
I don't want to waste your time or take this issue onto a tangent of writing CSS, but your solution won't work with responsive layouts. And as such that's not a solution in this day and age.

[https://codepen.io/anon/pen/YZKZjV?](https://codepen.io/anon/pen/YZKZjV)

Thinking laterally I could solve this issue with some js or jQuery but that's a route I'm less keen on for the sake of simplicity & resilience.

**Comment by dereklieu** [comment]
No worries. Just trying to help you find a solution. 

I'm not keen to support this feature request. I believe Prose should be a platform agnostic editor, and so addressing issues that are really issues with Kramdown/Jekyll is, to my mind, scope creep.

I hope that this issue generates enough momentum for either the Jekyll or Kramdown maintainers to fix it on their end (or perhaps make it configurable), and in the meantime that you can find a way to make your layout work.

**Comment by wesort** [comment]
Thanks and that's all fair enough.

**Comment by mrshannonyoung** [comment]
For anybody coming here looking for Kramdown wrapping `<img>` in `<p>` tags, you can use the following in your Markdown file:

```
{::nomarkdown}
image
{:/}
```
