### ISSUE TITLE
Allow for easy customizing of self deployed Prose instances

### ISSUE THREAD

**Issue by bnvk** [prose/prose#1016]
While **Prose** has a beautiful tool, logo, and name (for the tool), when one deploys their own instance (for a more customized use) it would be great if it could be customized in some small visual ways. Here are some suggestions:

- Custom name, logo and description
- Custom header bar
- Custom footer links

While one could just modify the original files and compile it, it would certainly be easier for non-front-end dev to deploy and simply change a few values in a `config.json` file.

**Comment by mikemorris** [comment]
Supporting white-labelling out of the box isn't really a priority, but you're welcome to fork this repo to change the logo, header and footer for your own instance.

**Comment by bnvk** [comment]
@mikemorris that makes sense (it's not a priority). I know I can do this in a 
fork, but I worry that method can cause my fork to break on pulling in updates.

Would Prose be open to the idea of merging in something well written which 
allows this functionality via a few lines in a `config.json` file?
