### ISSUE TITLE
Dependency Error: rdiscount

### ISSUE THREAD

**Issue by ecupaio** [prose/prose#1022]
**Problem:** I forked the repo, installed jekyll, and ran `jekyll serve --watch`which resulted in a failed build. 

**Solution** I added `gem "rdiscount"` to the Gemfile, ran `bundle` and it worked! 

It looks like rdiscount is the default markdown for this Jekyll theme and running `gem install rdiscount` did not work. Please add `gem "rdiscount"`to the Gemfile to fix

**Comment by mikemorris** [comment]
Prose isn't a Jekyll project itself (it's a "CMS" for editing Jekyll sites) and thus has no `Gemfile`. This ticket should probably be opened in the repo of the project you were trying to edit, not Prose.

**Comment by ecupaio** [comment]
So the page failed to build on github when I edited a post on the Jekyll site. I ran it locally (like the instructions said to do) to see what the issue was. Lo and behold, it was the markdown format in the config. Now it builds!
