### ISSUE TITLE
Disable differ via config

### ISSUE THREAD

**Issue by dfcreative** [prose/prose#1023]
Hello @prose team!
We heavily use prose for [ttbagroup](https://github.com/ttbagroup/ttbagroup.github.io) website, and we have tons of pages heavy-loaded with html generated from site-generator. Editors complain that when they are going to commit fat change via prose.io interface, it just hangs so that they have to kill chrome tab and do update via github directly.

As I've figured out, the reason is diffing - for large change it takes too long.
Can we possibly disable diffing of some subfolders via `_config.yml`, as we do with metafields?

Thanks!

**Comment by dereklieu** [comment]
Hey @dfcreative thanks for opening this ticket. I think the right way to handle this is to just hide the diff when it's too big, the same way Github does. 

Can you give me an example of how a big a diff you're talking about? Roughly how many lines of code are you changing?

**Comment by dfcreative** [comment]
Hi Derek, thank you for response. Example file: https://github.com/ttbagroup/ttbagroup.github.io/blob/master/pages/advertising.html, I would estimate it 1.5k lines. In some reason github handles same diffs fine, whereas prose just hangs, as if there is some O(n*n)  happening. I would appreciate help with that!

**Comment by dereklieu** [comment]
I looked into this a bit. Prose uses [jsdiff](https://github.com/kpdecker/jsdiff) for this feature, and `#diffWords` is what's eating up the main thread here.

![screen shot 2017-04-24 at 10 49 12 am](https://cloud.githubusercontent.com/assets/1590802/25331745/0b962410-28dc-11e7-8b30-0548e1cb845c.png)

Looking a bit closer, it looks like `clonePath` is particularly expensive. 

![screen shot 2017-04-24 at 10 53 58 am](https://cloud.githubusercontent.com/assets/1590802/25331865/73b58f22-28dc-11e7-9714-dddd3b30ba52.png)

The bundled version of `diff` is pretty old so I'm going to see if updating this dependency makes this work any faster.

**Comment by dereklieu** [comment]
Updating the version does nothing, however using the `#diffLines` method instead of `#diffWords` speeds this up dramatically. 

The result is something like this, which I think is acceptable, and also how Github shows diffs:

<img width="519" alt="screen shot 2017-04-24 at 11 40 27 am" src="https://cloud.githubusercontent.com/assets/1590802/25333622/dc77cda8-28e2-11e7-9c0d-5481f194cc6a.png">

**Comment by dereklieu** [comment]
I'm inclined to just switch the method to `diffLines` for everything and keeping the diffs consistent for every file, and not worry about looking at the size of the file to determine whether to use the slower algorithm or not.

**Comment by dfcreative** [comment]
Sweet, thanks a lot!
