### ISSUE TITLE
How to open a specific repo or a subfolder in that repo by default when opening prose.io

### ISSUE THREAD

**Issue by Sandeep3005** [prose/prose#1024]
Real newbie with prose but my task is to open a specific repo when a user from our site open prose.io.

I have forked prose from GitHub but no idea how to proceed, Can someone guide me on this?

Should I run it locally or need to change in any configuration file. How to run and test my forked repo of prose.io

Need real help on this

**Comment by dereklieu** [comment]
Do you want to host your own version of Prose, or just use prose.io? If you just want to use prose.io, you'll just need to authorize with Github, then visit a repo using prose.io/#/USER_NAME/REPO_NAME. For instance, http://prose.io/#prose/prose

**Comment by Sandeep3005** [comment]
Hi @dereklieu thanks for responding. I was digging in repo and found this md file 
prose/DEPLOYMENT.md

Can I run locally on localhost:3000 by instruction mentioned here
https://github.com/prose/prose/blob/master/DEPLOYMENT.md

also is there any way to open a specific folder 

One more thing This is what I wanted to let me know is this possible 

When I go to prose.io, I see all my repositories. forked/prose - is an exact copy of prose.io. 
When users open my version of forked/prose, I'd like them to go directly to https://github.com/Sandeep3005/prose/master/webapp/pages/docs instead of seeing all their repositories.

Is this possible .
Let me know , need help here sir

**Comment by dereklieu** [comment]
@Sandeep3005 there's no way to limit the ability of a user to see whatever repo's they've authorized Prose to access. I'm not sure what the best thing for your use case would be, but maybe it's creating a separate account that only has the one repo attached to it, then directing all your users to login in with that. 

You can run prose locally following the steps here:
https://github.com/prose/prose/blob/master/CONTRIBUTING.md#install-steps

The deployment directions are for setting up Gatekeeper, which you need to set up if you wish to deploy your own version of Prose.

Once again, there is no way in Prose to redirect to a specific repo or folder after logging in. You'll have to train your users on how to properly do that.
