### ISSUE TITLE
Broken link on http://prose.io/#about

### ISSUE THREAD

**Issue by dregad** [prose/prose#1035]
The `see the Prose contributing guidelines.` link (https://github.com/prose/prose/blob/gh-pages/CONTRIBUTING.md) yields a 404 - should be https://github.com/prose/prose/blob/master/CONTRIBUTING.md

**Comment by mikemorris** [comment]
This would need to be updated in https://github.com/prose/prose/blob/78d0b67f32378d36f4f9ade7c04809fe1e02813b/translations/application.yaml#L260 and ensure the updated link ends up in the translation files as well.

**Comment by janpio** [comment]
I wanted to fix this, but am not sure how: Can the fix be done directly in the repo in all language files or does the first change have to be done in the "master" file and then be translated via transifex?

**Comment by mikemorris** [comment]
> the first change have to be done in the "master" file and then be translated via transifex
^ I'm pretty sure this is what needs to happen @janpio
