### ISSUE TITLE
http://bootstrap.prose.io/?

### ISSUE THREAD

**Issue by janpio** [prose/prose#1039]
What is this at http://bootstrap.prose.io/?

**Comment by mikemorris** [comment]
This looks possibly related to the warning in https://help.github.com/articles/setting-up-a-custom-subdomain/#configuring-a-cname-record-with-your-dns-provider

> **Danger:** Do not use wildcard DNS records (e.g. *.example.com) with GitHub Pages! A wildcard DNS record will allow anyone to host a GitHub Pages site at one of your subdomains.

**Comment by janpio** [comment]
Yep, looks like it:
https://github.com/search?q=%22bootstrap.prose.io%22&type=Code&utf8=%E2%9C%93

Seems https://github.com/prose/bootstrap once existed there:
> We've created a simple template that you can use as a starting point, [Prose Bootstrap](http://bootstrap.prose.io). All you have to do is creating a fork of the [repository](http://github.com/prose/bootstrap) and give it a suitable new name. Please follow the steps described on the Bootstrap homepage. If you are already maintaining a Jekyll page you can skip this step. 

https://github.com/shawndotty/shawndotty.github.com/blob/e8fee04fb8a8e3180739d785cf3e2a6b9f494b9c/_posts/help/2012-06-20-getting-started.md

I can't find the actual repo currently controlling the content, maybe it is private? 

But: Should be fixed...

**Comment by mikemorris** [comment]
I'm guessing bootstrap became https://github.com/prose/starter a while ago, but yea maybe @dereklieu can take a look at DNS settings to fix this.

**Comment by janpio** [comment]
Removing the bootstrap entry in the DNS should be enough if this subdomain shouldn't be used any more. Right now it is (probably accidentally) "hijacked" by another user.

**Comment by olafveerman** [comment]
It was indeed a rogue entry in the DNS config. I just removed the bootstrap `CNAME`.

cc @dereklieu

**Comment by mikemorris** [comment]
@olafveerman @dereklieu Did the old DNS entry get removed too?

**Comment by olafveerman** [comment]
The entry was removed from the DNS config. We're not using a wildcard, nor are there any subdomains configured. The config only contains 2 A records that point the bare domain to GH's ip.

**Comment by dereklieu** [comment]
bootstrap.prose.io is no longer working.
