### ISSUE TITLE
Missing en translation: actions.commits.update

### ISSUE THREAD

**Issue by ImaCrea** [prose/prose#1042]
Hi folks,
we absolutely love Prose here at MailTape.

We just noticed a little bug recently : there seems to be missing a translation for the actions.commits.update

It's messing with all our commit title as you can see [in our repo](https://github.com/MailTape/MailTape.github.io/commits/master)

Would be great if it could be fixed 🙏

peace

**Comment by levineux** [comment]
I'm running into the same issue as well.
![image](https://user-images.githubusercontent.com/8993222/28093190-ead48f22-669e-11e7-8926-98ec1f4408c8.png)

**Comment by dereklieu** [comment]
Regression from #1037, need to generate new translation files.
