### ISSUE TITLE
Prose not logging me in

### ISSUE THREAD

**Issue by ethanchewy** [prose/prose#1045]
When I log into Prose and authorize it with my github auth, I am redirected to this page: http://prose.io/?code=3696e3687733b038d5ae and nothing appears

Here are the errors via inspect element:

"Failed to load resource: the server responded with a status of 503 (Service Unavailable) https://prose-gatekeeper.herokuapp.com/authenticate/3696e3687733b038d5ae"

"XMLHttpRequest cannot load https://prose-gatekeeper.herokuapp.com/authenticate/3696e3687733b038d5ae. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://prose.io' is therefore not allowed access. The response had HTTP status code 503."

It has been working yesterday and the days before. Any help would be highly appreciated!

**Comment by dereklieu** [comment]
Confirmed, thanks for reporting. Looking at Heroku now.

**Comment by dereklieu** [comment]
Update: I never did find out who owns the current prose-gatekeeper heroku app. It's not under Development Seed's account. I contacted Heroku support to see if they can tell me who the owner is. 

In the meantime, I am redeploying gatekeeper under Development Seed's Heroku account and will be switching the url that Prose.io talks to, to the new deployment.

Once Heroku contacts me with the contact for the previous owner, I'll contact them to remove the old deployment.

cc @ianschuler @mikemorris

**Comment by dereklieu** [comment]
Redeployed. Prose.io working again.

**Comment by mikemorris** [comment]
It may have been under @michael's personal account or something @dereklieu, as I believe gatekeeper predated the redesign of prose.io.
