### ISSUE TITLE
Default value for select metadata

### ISSUE THREAD

**Issue by nickmccurdy** [prose/prose#1047]
All of the metadata configuration fields except select and multiselect have a default `value` field in the docs. I have a site where select is used for Jekyll blog post categories and all posts have a default category. It would be helpful if I could start the select with the value(s) that I use most frequently, similarly to how the other fields work.

**Comment by dereklieu** [comment]
+1 this would be a great thing to have.

**Comment by dereklieu** [comment]
I looked into this and it's very straightforward. It's just a matter of sending a `value` to the initial render from template. I started a branch [here](https://github.com/prose/prose/tree/default-select-value) that implements this feature for select elements. Left to do are multiselect elements and some quick unit tests.

**Comment by nickmccurdy** [comment]
To anyone else looking at this issue, this is now deployed on prose.io and working perfectly.

@dereklieu Would you mind documenting this in https://github.com/prose/prose/wiki/Prose-Configuration or would you like me to try?

**Comment by dereklieu** [comment]
Ah yeah I'll edit the wiki tomorrow, thanks for the reminder.

**Comment by dereklieu** [comment]
Just added a note to the docs.
