### ISSUE TITLE
Missing en translation issue in help->miscellaneous

### ISSUE THREAD

**Issue by InfiniteCoder** [prose/prose#1061]
Under the help link on the page for creating posts, there is a translation issue, which causes one option under the miscellaneous category to show "Missing en translation: dialog ....". Clicking it causes the page to redirect to explore projects page, and all unsaved data is lost.
![](https://i.imgur.com/qxP0gat.png)

Errors from developer tools console in firefox,
```
Missing en translation: dialogs.help.miscellaneous.content.shortcuts.content locale.js:25:49
	missing http://prose.io/locale.js:25:49
	t http://prose.io/locale.js:38:16
	[19]</n.exports http://prose.io/dist/prose.js:2:22861
	markdownSnippet http://prose.io/dist/prose.js:4:31501
	dispatch http://prose.io/dist/prose.js:32:32150
	a http://prose.io/dist/prose.js:32:28212

```

**Comment by babbitt** [comment]
Confirmed that merging #1145 solved this issue and will hopefully prevent any like it from emerging again via more thorough tests.
