### ISSUE TITLE
Config-setting: 'site'

### ISSUE THREAD

**Issue by exoji2e** [prose/prose#1085]
Hi!

I don't fully understand the [description](https://github.com/prose/prose/wiki/Prose-Configuration) of the config element `site`: "This field accepts a list of absolute .JSONP paths to content that is loaded during Jekyll live previews. This is particularly useful for building out tags or categories that should be present during preview.". I can't find any usages of it in other repositories using prose.

I have defined my own tag, to enable the command inside markdown `{% img /path/to/img.png width:50%; %}` To set `style="width:50%;"` on an image included in a post. I have a [ruby script](https://github.com/SurgeonsPerspective/SurgeonsPerspective.github.io/blob/master/_plugins/tag_img.rb) inside my `_plugins`-folder. This becomes rendered at [my site](https://surgeonsperspective.github.io/blog/2018/08/30/first-prose-post/). What should I provide under `site` to make prose render the tag inside the preview?

I have tried to use the config element like [this](https://github.com/SurgeonsPerspective/SurgeonsPerspective.github.io/blob/a5f7f191f0f56c9967c29f34b97445b9b8a7dc22/_config.yml#L16):

```
site:
  - '_plugin/tag_img.rb'
```

My understanding is that this is the use case of the element `site` inside the config: "This is particularly useful for building out tags or categories that should be present during preview."

**Comment by dereklieu** [comment]
Hi @exoji2e very good question - unfortunately I can't find references to this particular configuration in the code. I would guess this to be a hold-over from an earlier version of Prose that is no longer supported. 

I will say that your use case, which is to execute a ruby plugin during live preview, would not be possible, given that Prose does not have a back-end (aka server) component, and thus no environment in which to execute that code.

I would suggest using a CSS stylesheet to achieve your style outcomes, and applying that style widely to your content container, or in a more targeted manner ie writing html in your markup.

I'm going to remove this section from the configuration wiki.
