### ISSUE TITLE
I have made a portfolio. It's scrolling in desktop(every browser) properly but when i am opening it in my mobile phone browsers, it's not scrolling properly. Except scrolling there is two more issues - experience and resume is not loading and opening respectively.

### ISSUE THREAD

**Issue by glob4lh3ll** [prose/prose#1090]
https://glob4lh3ll.github.io/rohit_rathaur.github.io/
it is the link of my portfolio. And the repo link is
https://glob4lh3ll.github.io/

I have also opened that issue in my issue but till now I have not got any answer. Please help me. I will be highly obliged to your act of kindness.

**Comment by dereklieu** [comment]
Please only open issues here that relate to Prose, the content authoring tool. Thanks.
