### ISSUE TITLE
Problem opening folder of Chinese character in name

### ISSUE THREAD

**Issue by hmua** [prose/prose#1130]
When open a folder of Chinese named,
get failed and showing an URL-encoded folder name

![Screenshot_2022-09-15-17-35-53-378_com.android.chrome.jpg](https://user-images.githubusercontent.com/38511582/190372494-d2a8e3a7-2198-4f0d-a865-629c8a1b6e09.jpg)

Just a simply refresh will get corrected

![Screenshot_2022-09-15-17-35-41-511_com.android.chrome.jpg](https://user-images.githubusercontent.com/38511582/190372909-ae2c5053-f9df-4c8d-b276-9387b2c78afd.jpg)

Have tested on Android+Chrome and iOS+Firefox 😊

**Comment by babbitt** [comment]
Hi there @hmua! I know it's quite late but I'm just starting to work through the backlog here in my free time. Can you provide a public repo so I can reproduce this issue and work on a fix?

**Comment by babbitt** [comment]
Finally got around to this. The [link you provided](https://prose.io/#hmua/hmua.github.io/tree/main/%E5%BD%B1%E8%A7%86) appears to be working. Hopefully better late than never :)
