### ISSUE TITLE
Insert Link functionality broken

### ISSUE THREAD

**Issue by helrond** [prose/prose#1152]
**Describe the bug**
The ability to insert links in Markdown files is broken in Prose.io. Clicking the Insert button in the Insert Link dialog redirects you to your root Prose.io page and does not add a link.

**To Reproduce**
1. Open a Markdown file in Prose.io
2. Click on the Insert Link button in the toolbar and enter values in the fields.
3. Click the "Insert" button in the dialog.

**Expected behavior**
A properly-formatted link should be created in the Markdown file at the cursor.

**Desktop or Mobile Device (please complete the following information):**
 - OS: macOS Monterey 12.6
 - Browser: Chrome
 - Version: 121.0.6167.160

**Bonus points**
Were there any error messages in the browser developer console?
- I checked and did not see any error messages.

**Comment by babbitt** [comment]
Hi there. Thanks for bringing this to my attention. I found some time to take a look at this issue and it should be resolved as of the PR above. Changes are live at [Prose.io](https://prose.io). :)

**Comment by helrond** [comment]
Thank you @babbitt!
