### ISSUE TITLE
Prose should not require access to private repositories

### ISSUE THREAD

**Issue by grk** [prose/prose#126]
Since gh pages are public by default, prose shouldn't request access for accessing private repositories (Update your public and private repositories (Commits, Issues, etc).)

**Comment by fulldecent** [comment]
@anandthakker Thank you, this fix looks great!

**Comment by brandonparsons** [comment]
Thank you for the update @anandthakker - I was sad for a minute there as I wanted to use this for an organization and your edit didn't show up in my email tracker :)

**Comment by PabloReyes** [comment]
Hey, I just read this now.

That's looks awesome @anandthakker ! Thank you for the support.

I'll give it a try ;)

**Comment by mikemorris** [comment]
Closing this as it should be resolved by @dhcole's merged pull request. GitHub also recently rolled out [organization-approved applications](https://github.com/blog/1941-organization-approved-applications), allowing organization admins to restrict access to third-party applications to a specific whitelist.

**Comment by md5** [comment]
@mikemorris Do you mind if I ask how #815 resolves this?

I understand that the organization-approved applications feature can be used to mitigate the issue, but I don't think it really resolves it.

In my case, I have access to nearly a dozen Github organizations owned by my employer's clients, most of whom have primarily private repositories. We have recommended using the organization-approved applications to our clients or turned it on for them ourselves where appropriate, but having to ask them to turn on this feature because I want to use a product to manage my personal blog is untenable in my opinion.

Unfortunately, I won't even be able to try out Prose.io unless or until this situation changes. I'm sure there are many other developers who work as consultants that are in the same situation I'm in.

**Comment by md5** [comment]
I'll also just add that turning on the organization-approved application feature has consequences that need to be dealt with in an orderly fashion:

> ### [Setting up third-party application restritions](https://help.github.com/articles/about-third-party-application-restrictions/#setting-up-third-party-application-restrictions)
> When an organization admin sets up third-party application restrictions for the first time:
> * **Applications that are owned by the organization** are automatically given access to the organization's resources.
> * **Third-party applications** immediately lose access to the organization's resources.
> * **SSH keys created before February 2014** immediately lose access to the organization's resources (this includes user and deploy keys).
> * **SSH keys created by applications during or after February 2014** immediately lose access to the organization's resources.
> * **Hook deliveries from private organization respositories** will no longer be sent to unapproved applications.
> * **API access** to private organization resources is not available for unapproved applications. In addition, there is no create, update, or delete access to public organization resources.
> * **Hooks created by users and hooks created before May 2014** will not be affected.
> * **Forks of organization-owned repositories** are subject to the organization's access restrictions.

**Comment by mikemorris** [comment]
@md5 #815 is completely unrelated to organization-approved applications. At initial authorization, it should prompt the user with a dropdown to select either public and private repo access (using the `repo` scope), or just public repo access (using the `public_repo` scope). https://developer.github.com/v3/oauth/#scopes

**Comment by md5** [comment]
@mikemorris Thanks for taking the time to clarify! :metal:

**Comment by aioue** [comment]
I just tried prose and was asked for access to private repos or nothing. Am I missing something?

**Comment by ApolloNet** [comment]
I could not write/save markdown files in an organization repo i own.

What i did to unlock :
 - logout from prose.io
 - copy the URL of the green button at the bottom right
 - changed the parameter &scope to : user,public_repo
 - paste the new URL in my browser
 - changed the permissions granted on organizations i own
