### ISSUE TITLE
Live preview?

### ISSUE THREAD

**Issue by bootstraponline** [prose/prose#139]
Any plans for live preview of markdown?
- [stackoverflow](http://www.stackoverflow.com) 
- [notepag.es](http://www.notepag.es)

**Comment by fulldecent** [comment]
Is this related to `siteurl` at https://github.com/prose/prose/wiki/Prose-Configuration

**Comment by vassudanagunta** [comment]
Check out [Typora](http://www.typora.io). Apparently it's actually coded in Javascript. It's [not (yet) open source](typora/typora-issues#16), but the author has [a support site on GitHub](https://github.com/typora). At the very least people can see for themselves what it's like to to WYSIWYG Markdown in practice. I've been using it for well over a year.
