### ISSUE TITLE
422 Unprocessable Entity - Update is not a fast forward

### ISSUE THREAD

**Issue by tylermenezes** [prose/prose#148]
When attempting to save a file using prose.io, the PATCH call to https://api.github.com/repos/[org]/[repo]/git/refs/heads/master fails with error 422 Unprocessable Entity. The message in the JSON response is "Update is not a fast forward".

This occurs whether attempting to create new files, or updating existing ones.

**Comment by parker-codes** [comment]
> 
> 
> We're aware of this issue. It takes up to 30seconds until the GitHub API (read) recognizes a change. We're cachine the latest commit sha on the client-side, so we're not running into the non-fast-forward update issue. However this error occurs if you save a file, doing a hard refresh (it loads the outdated version) and then hit save again. I'm sure the GitHub guys are working on decreasing the latency, but until it's solved on their side, the problem remains.
> 
> Oh and for the same reason, when deleting a file it still appears in the file listing for ~ 30 seconds.

This helped us solve our GitHub API issues. We were pulling "the most recent" commit info before making more updates, but due to this race condition, it was not actually the most recent. We did the same as @michael and stored the latest commit SHA for reference later and it fixed our issue.
