### ISSUE TITLE
Spell Check in Body

### ISSUE THREAD

**Issue by joehand** [prose/prose#169]
The browser's spell check does not work in the body of .md posts (haven't checked other formats). 

I understand why spell check could be a hinderance for writing code. But if this is meant to be a writing-oriented CMS spell check should be available.

Chrome 20.0.1132.47 beta

**Comment by kerim** [comment]
Sorry to see that this is closed. Hope someone can re-open it or suggest another solution.

**Comment by orschiro** [comment]
Has anyone tried this solution?

https://github.com/codemirror/CodeMirror/issues/1017#issuecomment-122308718

**Comment by eduncan911** [comment]
@orschiro i think most of solutions use `type.js`, which we were trying to avoid.  we want Chrome's built-in spell checker.

**Comment by orschiro** [comment]
> over the years since this issue was created, and closed, i've just switched to doing everything in Vim with markdown and html plugins. allows me to do everything remote that i need.

You do everything in Vim and then paste it back into the web browser?

**Comment by eduncan911** [comment]
I was using Prose to edit markdown for GitHub pages (Jekyll/Octopress, which is a ruby framework for making static websites).  

I've just reverted back to CLI, and push the updates up with git instead.  No web browser involved.  ssh to a box from anywhere, make edits, done.

**Comment by kerim** [comment]
Another new option is forestry.io (I haven't used it yet, but happened to learn of it right before this thread popped up from the dead.)
