### ISSUE TITLE
Smart paste option: formats into correct markdown/liquid

### ISSUE THREAD

**Issue by joshkerr** [prose/prose#201]
This takes the value in the clipboard and pastes it into the document with correct markdown.  So if I have a link to imgur in my clipboard, doing "smart paste" would past it as a photo using markdown.

If you really wanted to make this cool you would let me define templates that can reformat clipboard content.  A common use case would be a person who pastes lots of snippets of ruby code.  So they define a template that sets liquid tags for highlighting code with language set to ruby.  When they do a smart paste, they select their template, and the clipboard contents are added in the right spot and inserted into the document.

**Comment by alexpetralia** [comment]
Out of curiosity, was this ever added as a feature? (If not, no problem, just curious if I am missing it somewhere.)
