### ISSUE TITLE
Footnotes in Markdown preview

### ISSUE THREAD

**Issue by tjohns** [prose/prose#248]
The Markdown preview for Prose.io doesn't render footnotes, even though they're supported by Github's Jekyll installation.

(Markdown supports footnotes using this syntax: [^1], similar to a hyperlink.)

**Comment by bfaguy** [comment]
I'm having same issue as @tjohns. were you able to figure it out? 
Internally, we use redcarpet with the footnotes option.  Just to understand how prose.io works, do we need to configure any setting? Or is the footnote option on by default?

**Comment by dereklieu** [comment]
@bfaguy Hey, happy to look into this if you could post some code blocks that aren't producing the desired results. Thanks!
