### ISSUE TITLE
Problem with tags metadata (or arrays metadata)

### ISSUE THREAD

**Issue by davidgil** [prose/prose#415]
Hi,

i have some custom content types that use tags metadata field to relate different posts.

If i use this syntax in my .md file:

tags:
- Jordi Cussó Porredón
- Enrique Baca Baldomero
- Fancesc Torralba
- Jorge Úbeda

Prose.io transform its contents when i save data in a single string broking this funcionality.

  tags: "Jordi Cussó Porredón,Enrique Baca Baldomero,Fancesc Torralba,Jorge Úbeda"

Field is defined in this way in _config.yml:
      - name: "tags"
        field:
          element: "text"
          label: "Profesores"
          value:
            - "Nombre del tutor (como el campo title del profesor)"
            - "Nombre del profesor (como el campo title del profesor)"
Here there is a sample:

https://raw.github.com/dontknow-net/dontknow-net.github.io/master/_posts/cursos/2013-05-29-nacionalismo.md

any idea what i can do?

Best
David

**Comment by fulldecent** [comment]
See new feature

> alterable: (optional boolean) true or false whether a user can add additional values. Useful for tags.

Documented here: https://github.com/prose/prose/wiki/Prose-Configuration
