### ISSUE TITLE
Allow specifying content for new files via url query params

### ISSUE THREAD

**Issue by agius** [prose/prose#435]
I'd like to create a bookmarklet or Chrome extensions to make 1-click publishing for Jekyll blogs easy. If I could just point a request to prose.io/#{account}/{repo}/new/master/_posts?content={content}&metadata={metadata} , this would be awesome. Digging around, I'm not sure it's even possible without support in app, as it would require injecting code that interfaces with CodeMirror.

Thoughts?

**Comment by fulldecent** [comment]
Since #437 was close as wontfix, recommending to close this issue too
