### ISSUE TITLE
android browser support

### ISSUE THREAD

**Issue by nibl** [prose/prose#498]
Are there any plans to support android browsers in the future? I have tried 4 different browsers on android 4.2 and unfortunately prose is unusable.

Paste and select are extremely difficult or impossible and icons are often missing or do not appear to react.

**Comment by mattymaloney** [comment]
I don't see how this is a dupe of #430. The problem described in this issue was not resolved when #430 was resolved.

Even now, we can not select text while editing a post in Chrome for Android. Editing/selecting does work fairly well in UC Browser.
