### ISSUE TITLE
Session storage keys aren't namespaced to site

### ISSUE THREAD

**Issue by edrex** [prose/prose#519]
I Just noticed this. It would be nice if the session storage keys used something more unique, such as a URL, for unsaved versions of files. If there is no easily accessible per-file URL then prepending the repo name would also work.

Currently I imagine if you open a file with the same name (say README.md) in another repo it might erroneously load the draft from the first site (although I haven't tested it yet)

**Comment by dereklieu** [comment]
Current path is `user/repo/branch/directory/filename` which is adequate. Closing.
