### ISSUE TITLE
Bitbucket port

### ISSUE THREAD

**Issue by benedfit** [prose/prose#545]
Gonna get my head around the code base, and explore if a Bitbucket port is possible

**Comment by fulldecent** [comment]
Is anyone inspired to work on this project?

Recommending to close this issue as out of scope

**Comment by benedfit** [comment]
I never picked it up, so going to close, and let someone else take up the mantle

**Comment by RONNCC** [comment]
Is there any possibility of this being reopened?

**Comment by bpmottathai** [comment]
+1 for this project. Is there any alternative available?
