### ISSUE TITLE
Poor handling of revoked GitHub tokens

### ISSUE THREAD

**Issue by MTecknology** [prose/prose#606]
If I navigate to http://prose.io/, click Authorize, log into Github, and then authorize the application, I'm kicked back to a page that says "Error while loading data from Github. This might be a temporary issue. Please try again later." I can't get further than this. I tried revoking access and trying again but got the same place. I tried throughout the entire day and can't get past that. I'm offered nothing to help debugging.

**Comment by michaelkirk** [comment]
Just got bit by this, though I never revoked access to the app.

![proseio-401](https://cloud.githubusercontent.com/assets/217057/9184301/41285764-3f69-11e5-92e1-9cfb4b71917c.png)

The work around was to clear my prose cookie.

**Comment by dereklieu** [comment]
I get this occasionally too, and would like there to be a Re-Authorize button in that dialog message.

**Comment by phillipadsmith** [comment]
> I get this occasionally too, and would like there to be a Re-Authorize button in that dialog message.

+1

**Comment by jmatsushita** [comment]
+1 Just bumped into this as well after recreating a new github organisation and new application on the same prose server. I agree that a Re-Authorize button would help the hassle of deleting the cookie (or more importantly, telling my prose users to delete their cookie...)

**Comment by phillipadsmith** [comment]
@dereklieu Just putting a placeholder here because I haven't looked at it closely, github-secret-keeper https://github.com/HenrikJoreteg/github-secret-keeper

**Comment by MTecknology** [comment]
I'm re-closing this as the original report was not a temporary issue, it was a permanent failure where first login was never possible. It appears a new issue is being discussed and a new issue should be created.
