### ISSUE TITLE
Metadata isn't saving

### ISSUE THREAD

**Issue by scottandjames** [prose/prose#623]
I've been using prose.io for close to a year now, and usually add metadata in the side tab like this...

layout: post
author: Staff
title: "This Foo is the Fooest"

For the last few days, when I add metadata like that and click save, it doesn't save and I get sent back out of the post screen and to my own github home screen. This has happened on firefox and safari. 

Is this something that has come up for other people? Is there a fix I can try? 

Note: I'm the writer and don't know code, but the coders I work with didn't find an obvious issue, so I'm digging for information or leads. Thanks.

**Comment by MartinLyne** [comment]
I don't know if it's related to this, but I can't seem to save any metadata. Fill it in, save, go back to it, open meta data, empty. I'm a new user so not sure if I'm missing something.

I also noticed that a new post with metadata added is not saved at all. It says it commits, but nothing in github and nothing in drafts. If I make a post with no metadata, everything saves okay.

**Comment by phillipadsmith** [comment]
@dereklieu I'm getting this bug intermittently. If I create a new file, copy & paste the following into the Raw Metadata field:

```
layout: post
author: Staff
title: "This Foo is the Fooest"
```

The meta data is updated and shown as ready to save (green).

If I open a new file and type anything into the Raw Metadata field, e.g.:

```
author: Staff
```
That is not shown as part of the meta data to be committed.

I've also occasionally has the change/commit show nothing, even though the default new file has lots of meta data, e.g.: https://github.com/phillipadsmith/starter/blob/gh-pages/_posts/2015-08-08-your-filename.md

Hope that's helpful.

Phillip.

**Comment by phillipadsmith** [comment]
@dereklieu Ignore the above. I had not run `gulp` again on your metadata-fixes branch. The meta data is saving correctly now.

**Comment by dereklieu** [comment]
@phillipadsmith awesome. I thought that was the case when I saw there weren't nearly enough tests in your screengrab :).

**Comment by phillipadsmith** [comment]
@dereklieu Classic n00b mistake. ;)

**Comment by dereklieu** [comment]
The raw metadata editor is working as of #862 and deployed to prose.io.
