### ISSUE TITLE
Metadata date saved as empty when adding an image.

### ISSUE THREAD

**Issue by juanpastas** [prose/prose#637]
Hi,

I saw #623. But I think that's not the same as this one.

These are the steps I follow:

1. Go to prose.io
2. Authorise Prose in Github.
3. Select my *.github.io repository.
4. I open a post to edit.
5. I click in the link add an image.
6. I commit that with default message.
7. Then page reloads and after a while I receive a mail from Github saying that build has failed.
8. I update my local copy of the repo and try `jekyll build`
9. I get  `Generating... error: no time information in "{}". Use --trace to view backtrace`.
10. I try to edit metadata in Prose and commit, but its does not work.
11. I edit front matter section in my local copy replacing the value of date from `{}` to `2013-11-15`, then I push and site is built correctly.

Do I have an error in my config:

```yaml
prose:
  rooturl: '_posts'
  # removed siteurl
  media: 'media'
```

Thanks.

**Comment by dereklieu** [comment]
Closed via #831
