### ISSUE TITLE
uncaught exception: JS-YAML: unacceptabe kind of an object to dump (undefined)

### ISSUE THREAD

**Issue by jmatsushita** [prose/prose#674]
Hi there,

When attempting to save posts (after fiddling with the _config.yml for this project https://github.com/TeamPanicButton/teampanicbutton.github.io/) I get the uncaught exception message in my browser's js console:
uncaught exception: JS-YAML: unacceptabe kind of an object to dump (undefined)

This happens on prose.io as well as our prose instance (running 1.1.0).

Can you help?

Jun
PS: In case it's related I also get TypeError: handleObj.handler.apply is not a function prose.min.js:11 in the console when loading a post.

**Comment by Floppy** [comment]
Likewise, I get this when trying to use the metadata editor. Once you've tried to edit metadata, prose dies completely and can't save, throwing this error. I tried to add just this to the metadata section:
```
title: Hello
```
