### ISSUE TITLE
Insufficient escaping of filenames and branch names enables XSS attacks

### ISSUE THREAD

**Issue by bburky** [prose/prose#699]
Insufficient escaping of filenames and branch names enables XSS attacks

Example:
http://prose.io/#bburky/xss

Repository:
https://github.com/bburky/xss

A public repository containing an XSS attack can be viewed (or iframed) by an authenticated prose.io user, compromising their GitHub account through any OAuth scopes they have authorized.

**Comment by dereklieu** [comment]
After visiting this site again with the newest deployment, I no longer get the dozens of alert messages I used to. Marking this as fixed.
