### ISSUE TITLE
Custom domain leading to GitHub pages 404

### ISSUE THREAD

**Issue by dav-s** [prose/prose#703]
Hi!

I just started using the prose.io website. In my short time with it, I found that when I click "View Site" on a project, it redirects me to a GitHub pages 404 page.

For example, I have a GH pages site [EpicDavi.github.io](https://github.com/EpicDavi/EpicDavi.github.io) that is connected via CNAME to my domain, [daviskr.com](http://daviskr.com).

When I authorize/log into prose.io, I see that that project has the option "View Site" next to "View Project". When I click on "View Site", I am redirected to the URL [prose.io/daviskr.com](http://prose.io/daviskr.com). This page is a 404 page for GitHub pages, stating "Page not found" and "There isn't a GitHub Page here." I don't think this was supposed to happen.

This issue also persists for other projects of mine that have GitHub pages. They redirect to the same 404 page but with the project name appended to the URL.

I am using FireFox 29.0.

Thanks!

**Comment by pgriesmer** [comment]
@EpicDavi I was having the exact same issue as you just now, but adding a CNAME file--as @mxstbr suggested above--fixed the problem. I just had to follow the directions on the Github Help page that he appended to his comment.

**Comment by khoad** [comment]
In my case, I had the CNAME file but somehow I created the CNAME file with exe permissions. After `chmod -x CNAME`, it worked for me.

**Comment by cs14rendra** [comment]
i had "madebysurendra.xyz" in my CNAME file, i changed it to "http://madebysurendra.xyz". i added two ip " 192.30.252.153, 192.30.252.154" in my A type and "cs14rendra.github.io" to CNAME on my DNS side. its working now.

**Comment by armujahid** [comment]
adding `permalink: /404.html` to the frontmatter fixed for me

https://help.github.com/articles/custom-404-pages/

**Comment by VMasanabo** [comment]
> i had "madebysurendra.xyz" in my CNAME file, i changed it to "http://madebysurendra.xyz". i added two ip " 192.30.252.153, 192.30.252.154" in my A type and "cs14rendra.github.io" to CNAME on my DNS side. its working now.

This worked for me.

**Comment by ctlove0523** [comment]
How to fix this:
The Host is not resolvable,please make sure the URL is correct.

**Comment by xiaohujiazi** [comment]
i had "xiaohujiazi.top" in my CNAME file, i changed it to "xiaohujiazi.github.io".
its working now.
