### ISSUE TITLE
Jekyll 2.0.0

### ISSUE THREAD

**Issue by mikemorris** [prose/prose#704]
http://jekyllrb.com/news/2014/05/06/jekyll-turns-2-0-0/

Need to test for breaking changes and clean up support around overlapping features ([YAML Front-Matter defaults](http://jekyllrb.com/docs/configuration/#frontmatter_defaults)) in a branch to be ready for when this lands in GitHub Pages.

/cc @parkr

**Comment by fulldecent** [comment]
Jekyll 2.0 has landed. Recommending to close this generic issue and treat new items as they come up
