### ISSUE TITLE
Error with "textarea" element type (OSX / Chrome 37)

### ISSUE THREAD

**Issue by sschafft** [prose/prose#766]
For some reason if the "textarea" field is selected it is wiping out the data associated with anything stored in that field. Setting it back to just "text" seems to solve the issue but the input area isnt ideal. 

Screencast: 
http://youtu.be/KwoXbfOXy9w

**Comment by paulhayes** [comment]
Would love to see this fixed!

**Comment by phillipadsmith** [comment]
@dereklieu This is still an issue, unfortunately. 
<img width="731" alt="editing__posts_2015-08-08-test-of-a-text-area_md_2015-08-08-test-of-a-text-area_md_at_gh-pages_ _prose" src="https://cloud.githubusercontent.com/assets/34128/9153025/3b1969f4-3df6-11e5-9881-4255e08250b1.png">

**Comment by phillipadsmith** [comment]
@dereklieu Ignore the last comment. Had not run `gulp`. https://github.com/prose/prose/pull/862 fixes the textarea issue for me, e.g.:
https://github.com/phillipadsmith/starter/commits/gh-pages/_posts/2015-08-08-test-metadata-save.md

**Comment by dereklieu** [comment]
Textarea fields are working as of #862 and deployed to prose.io.
