### ISSUE TITLE
Installing on Windows returns mkdir errors

### ISSUE THREAD

**Issue by tylerhou** [prose/prose#802]
Installing prose on Windows returns mkdir errors. This is because Windows `mkdir` by itself does not support the `-p` flag, and instead creates a directory *-p*:
![image](https://cloud.githubusercontent.com/assets/5315734/5551341/2bc2e042-8b96-11e4-9f1c-46f7182afbb6.png)

`gulpfile.js` invokes `mkdir -p` when it runs, causing the error on Windows. Even when there is a GNU version of `mkdir` on the user's path, the cmd builtin runs.

Fixes:

 - Encase `mkdir` in quotation marks, and have the user have the GNU version of `mkdir` on their path. Thus: `"mkdir" -p ...`
 - Use a plugin to make the directory. [node-mkdirp](https://github.com/substack/node-mkdirp) is one. Thus:

        var mkdirp = require('mkdirp');
        ...
        mkdirp('./dist', function (err) {
            if (err) console.error(err)
            else console.log('mkdir failed!')
        });

**Comment by mikemorris** [comment]
Good catch. This should be using `node-mkdirp` - PR please and I'll merge it.
