### ISSUE TITLE
Improvement: Apple Web App

### ISSUE THREAD

**Issue by enochappathurai** [prose/prose#803]
Improvement: Make Prose an Apple Web App
===================================

By inserting the following lines of code into each page, Prose could be saved to Home Screen and made a Web App:
&lt;meta name="apple-mobile-web-app-capable" content="yes" /&gt;
&lt;meta name="apple-mobile-web-app-status-bar-style" content="black" /&gt;

I hope that this will be implemented as there are not many sites/apps on iOS that allow for quick editing of documents especially on Github. If this is implemented, users will be able to easily access and change documents from more platform in an easier way.

Thanks for viewing this proposition for improvement,
Enoch.

**Comment by mikemorris** [comment]
I swear I had Prose saved as a bookmark/web app at some point on my iPad, should still be possible, this just isolates it in its own app/webview, right?

**Comment by enochappathurai** [comment]
Yeah Mike,

This makes it work in its own app instead of opening in safari.

enoch

**Comment by mikemorris** [comment]
If you can PR this into [`index.html`](https://github.com/prose/prose/blob/master/index.html) and test it to make sure it's working as you expect, I'll click the merge button.

**Comment by enochappathurai** [comment]
Pull Requested, Awaiting acceptance :+1:

**Comment by enochappathurai** [comment]
The page doesn't seem to be rendering what is on index.html in this repository. That is, it does not show the code for making it a web app. Here is a screenshot of the code that I see
![image](https://cloud.githubusercontent.com/assets/10068043/6056457/40730f94-ad65-11e4-87bb-e79c8c7d9db6.jpg)
As you can see, the code that has been merged is not seen in the screenshot that I took today.

Hope you can find what is making this happen. I think this might be something caused by the server getting an older version of index.html in this repository and displaying that as the prose.io page (or something like that). Good Luck!

**Comment by mikemorris** [comment]
It likely hasn't been deployed to the gh-pages branch, I'd like to remove the distinction between master and gh-pages at some point so this stops happening and merged means deployed.

**Comment by dereklieu** [comment]
@mikemorris on another project we've used codeship to deploy to gh-pages whenever we merge to master. Is this something we can set up with travis? (I see a travis.yml but haven't had much experience using it)

**Comment by mikemorris** [comment]
I'd be inclined to just drop `master` altogether and merge directly into `gh-pages`.
