### ISSUE TITLE
GitHub organization permissions changes

### ISSUE THREAD

**Issue by mikemorris** [prose/prose#812]
> You're using the following API endpoints:

> - List user organizations: https://developer.github.com/v3/orgs/#list-user-organizations

> On February 24, the behavior of these APIs will be changing. You can read more about these changes on our API blog:

> https://developer.github.com/changes/2014-12-08-organization-permissions-api-preview/

> We strongly recommend reading through this blog post, figuring out how these changes will impact your app, and updating the code accordingly.

/cc @prose/contributors

**Comment by fkostadinov** [comment]
We are running our own version of Prose (with some adaptations). Could you please specify more closely what changes will be necessary? Where does Prose actually access this list of user organizations?

**Comment by devinberg** [comment]
I get an error when trying to use prose.io that seems to be related to this issue.

> You need at least read:org scope or user scope to list your organizations.

**Comment by dereklieu** [comment]
@devinberg is this a console error you're seeing? As of [this](https://github.com/prose/prose/pull/963/files) we're using the newer organization endpoint for authenticated users.

**Comment by devinberg** [comment]
All I did was go to prose.io, authorize through Github, get returned to prose.io and see this error message.

**Comment by dereklieu** [comment]
Thanks for flagging this, will look into it further.

**Comment by rvernica** [comment]
Here is a screenshot of how it looks. It makes prose.io website unusable.

![403-forbidden](https://cloud.githubusercontent.com/assets/241185/16016427/def68f00-314f-11e6-8bfa-5004f7abbcd7.png)

**Comment by dereklieu** [comment]
@rvernica thanks for confirming, will have a fix for this today.

**Comment by dereklieu** [comment]
Fixed organization endpoint when scoped to public organizations only. The fix in effect takes care of the initial ticket as well.
