### ISSUE TITLE
GitHub OAuth scope public_repo allows broad access

### ISSUE THREAD

**Issue by pdurbin** [prose/prose#816]
It looks like commit e646a45d3760a38bb1b8bf46ddd120bb3cd67e94 added the GitHub OAuth scope `public_repo` which seems to allow broad access to users' personal repos and (potentially) to repos of organizations they are members of.

The description of the `public_repo` scope at https://developer.github.com/v3/oauth/#scopes is "Grants read/write access to code, commit statuses, and deployment statuses for public repositories and organizations."

When I click "Authorize on GitHub" from http://prose.io I see the text below:

"This application will be able to **read and write all public and private repo data**. This includes the following:

- Code
- Issues
- Pull requests
- Wikis
- Settings
- Webhooks and services
- Deploy keys"

And under "Organization access" I see "This organization allows the application to access organization data as described in the permissions above."

All this access being requested seems rather broad to me and I'm not sure if this is intentional. Prose will be able to write to settings and deploy keys? Here's a screenshot:

![prose](https://cloud.githubusercontent.com/assets/21006/6318960/ecc080c2-ba78-11e4-911c-d520ee5741e4.png)

**Comment by mikemorris** [comment]
This is actually narrower than the `repo` scope which was the only option before this change, and AFAIK this is the narrowest available scope that allows Prose to read and write to repositories.

**Comment by pdurbin** [comment]
See also [the comment](https://github.com/mozillascience/site/issues/11#issuecomment-75589627) by @arfon in reference to [a related blog post](http://crimsonfu.github.io/2015/02/22/owners-of-organizations-on-github-should-carefully-set-up-third-party-application-restrictions.html) I made yesterday. He talks about how scopes are limited but I still find the screenshot above terrifying. But whatever. :)
