### ISSUE TITLE
Allow for wider (responsive) editor

### ISSUE THREAD

**Issue by Naatan** [prose/prose#819]
On a large screen (1920) the editor is incredibly narrow. I tried simply setting the wrapping elements max-width to `1000` which alone made the experience feel a lot better.

It'd be nice if this could be handled more responsively, or even just make it flexible (min-width, max-width).

**Comment by mikemorris** [comment]
https://github.com/prose/prose/issues/644 is another issue hypothesizing what a responsive wide-screen setup could include

**Comment by Naatan** [comment]
That would also be very nice, but I'd still like a wider editor as well.

**Comment by rog1039** [comment]
I'd prefer this worked on first with the side-by-side preview a close second.

**Comment by dereklieu** [comment]
Closed #927
