### ISSUE TITLE
Reusing Prose.io as a customer CMS

### ISSUE THREAD

**Issue by daveas** [prose/prose#820]
I offer one-off website designs for small businesses and individuals. I usually set them up with a github hosted static page (because that is all many people need) and I do this for a one time fee or with a recurring annual fee if they need to make their site's repo private (to cover costs).

I would like to host a version of prose at cms.my-domain.com and add some custom styling. I would not charge and I would use the same license, include the copyright, etc. I would also restrict the access and create some special permissions (so that they can only edit posts on blogs).

Would that be alright?

**Comment by mikemorris** [comment]
Part of the reason we built Prose in the first place! :+1:

**Comment by tristen** [comment]
To be clear Prose is [BSD](http://choosealicense.com/licenses/bsd-3-clause/) licensed meaning you are free to fork and use for commercial use.

**Comment by daveas** [comment]
Fantastic. Many thanks for creating this!
