### ISSUE TITLE
Media path for uploading

### ISSUE THREAD

**Issue by aharris88** [prose/prose#821]
I have media set to "assets/uploads" in my [`_config.yml`](https://github.com/becbec1/becbec1.github.io/blob/1960e444932ac8abc59dc1c9d3921e5cd542a893/_config.yml) like so:

    prose:
      rooturl: "_posts"
      media: "assets/uploads"

And it shows those correctly on the right side of the media upload dialog, but when I go to upload, it still sets the page to "_posts" by default.

![screen shot 2015-03-23 at 9 14 02 pm](https://cloud.githubusercontent.com/assets/3266363/6795145/921c5d2c-d1a1-11e4-9217-768c74c254fb.png)

Why is that? Am I doing something wrong? I would expect it to set the default path to "assets/uploads".

**Comment by jfrankl** [comment]
Running into the same issue. Dragging and dropping the image into the editor seems to set the url to the media setting. Selecting and inserting sets the url to the current directory.

**Comment by aharris88** [comment]
Thanks, I'll try dragging as a work around for now. But this should be marked as a bug.

**Comment by jfrankl** [comment]
Dragging results in the other bug I experience, which is that the editor locks up. I can drop more items in, but I can't click into the text field to type more.

**Comment by jfrankl** [comment]
I just (https://github.com/prose/prose/blob/master/CONTRIBUTING.md#user-content-building--installing)[installed prose locally] and couldn't reproduce this bug on my local build.

**Comment by jfrankl** [comment]
I just [installed prose locally](https://github.com/prose/prose/blob/master/CONTRIBUTING.md#user-content-building--installing) and couldn't reproduce this bug on my local build.

**Comment by aharris88** [comment]
Same here. I don't see the bug when I run locally. I wonder what's up with that.

**Comment by stuarthannig** [comment]
Image uploads are still broken.

**Comment by holic** [comment]
Ran into this issue as well. Tried to reproduce locally, but it works as expected.

**Comment by dereklieu** [comment]
Seems like master was ahead of gh-pages when this was posted. This is now working as it should, tested on prose.io.
