### ISSUE TITLE
New organisations don't appear

### ISSUE THREAD

**Issue by paulhayes** [prose/prose#826]
After already using prose, and granting access to my account, I created an organisation this stubonly refused to show in prose, and even after manual putting http://prose.io/#org-name I still couldn't see the private repo I had access to. It wasn't until I revoked prose access and regranted it, that I was able to see the repo.

**Comment by mikemorris** [comment]
Possible that this is an limitation of GitHub's auth scopes, where an access token only gets scoped to the organizations associated with the user at creation time.

**Comment by paulhayes** [comment]
right, thanks for the fast response. I'm glad it wasn't a show stopper for
me. My main concern with prose at the moment is the very buggy metadata
support.

**Comment by dalareo** [comment]
I have change token (remove and authorize again) but new organization is still missing from groups menu on the right!

**Comment by dereklieu** [comment]
I looked into this just now and learned that the endpoint we're using, `users/:username/orgs`, lists organizations in which you are a **public member**. I believe when you join an organization, you are a private member by default.

[Change your membership](https://help.github.com/articles/publicizing-or-hiding-organization-membership/).

**Comment by mikemorris** [comment]
@dereklieu Can we switch this endpoint to list organizations for the authenticated user?

> This method only lists public memberships, regardless of authentication. If you need to fetch all of the organization memberships (public and private) for the authenticated user, use the [List your organizations](https://developer.github.com/v3/orgs/#list-your-organizations) API instead.
https://developer.github.com/v3/orgs/#list-user-organizations

**Comment by dereklieu** [comment]
@mikemorris Yes, caveat being that particular endpoint requires the user to be authenticated. Still, should be easy to fall back to using the current endpoint during unauthenticated sessions.

**Comment by dereklieu** [comment]
We're now using the authenticated endpoint, which shows all orgs you can modify. It's a welcome change, thanks for bringing this up all.

Can someone confirm if making/joining a new organization still requires a re-auth?

**Comment by dalareo** [comment]
@dereklieu not anymore!! great job guys!!

**Comment by easherma** [comment]
This doesn't appear to be working for me; I don't see any orgs even though I may be the owner/have permission to modify.
