### ISSUE TITLE
image does not upload

### ISSUE THREAD

**Issue by Buzzlightyear90** [prose/prose#827]
I am having a problem uploading images into the webpage and nothing is working. The entire page turns light grey and it is unresponsive. I have to resfresh the page everytime I want to upload the image and nothing else is added in the images folder. Even if I click upload, the page refreshes back to the homepage and the new image was never added into the images folder

**Comment by Buzzlightyear90** [comment]
I am still having problems with this image uploader

**Comment by Buzzlightyear90** [comment]
oh forget it, i'll solve it myself

**Comment by Koxzi95** [comment]
Sadly nobody who is a collaborator is answering anything. https://github.com/prose/prose/issues/743
