### ISSUE TITLE
Automatic Deployment

### ISSUE THREAD

**Issue by dereklieu** [prose/prose#835]
@mikemorris @tristen have you already discussed automatic deployment in the past? Personally I think it'd be nice to set up travis to push to gh-pages when a commit goes to master.

@prose/contributors I also think we should take another look at #434, setting up a dev version of prose.io for public testing before deploying major changes.

**Comment by anandthakker** [comment]
:+1: to both points, @dereklieu

**Comment by mikemorris** [comment]
Yes plz to automatic deployment, we should really just switch gh-pages to be the defaut branch and kill off master though.

Some sort of staging env would be nice for testing major changes, but most of the ideas in #434 seem overly complex for the benefit they would provide.

**Comment by dereklieu** [comment]
@mikemorris can you think of any blockers to just making that switch now? We should clear the pull request queue, but is there anything else?

**Comment by mikemorris** [comment]
Nope, just update [CONTRIBUTING.md](https://github.com/prose/prose/blob/master/CONTRIBUTING.md#submitting-pull-requests)

**Comment by parkr** [comment]
Niiiice.

**Comment by phillipadsmith** [comment]
@dereklieu Is this issue still open?

**Comment by dereklieu** [comment]
@phillipadsmith yup! Still need either an automated Travis deployment script, or to be able to wipe out the master branch, which would involve IMO closing the open pull requests.

**Comment by mikemorris** [comment]
@dereklieu I would suggest just making sure that `master` is deployable, then push it to `gh-pages` and kill `master`. Open pull requests can be recreated if they're still relevant.

**Comment by dereklieu** [comment]
@mikemorris one small issue is that `index.html` in master [doesn't use the minified version of prose](https://github.com/prose/prose/blob/master/index.html#L19) while gh-pages [does](https://github.com/prose/prose/blob/gh-pages/index.html#L19). 

I think killing `master` would mean serving the un-minified version (not a huge deal IMO) unless there's a smarter way to handle this.

**Comment by mikemorris** [comment]
@dereklieu Un-minified seems fine to me, ease of automatic deployment definitely outweighs the small file size savings.

**Comment by dereklieu** [comment]
@mikemorris awesome. Putting this on my to-do list.
