### ISSUE TITLE
Error trying to upload image

### ISSUE THREAD

**Issue by mhdomo** [prose/prose#839]
Dragging and dropping an image into a markdown file triggers an error. Using "Insert Image" in the toolbar, gives the same error.

Chrome: `Uncaught TypeError: Cannot read property 'media' of undefined`
Firefox: `TypeError: this.config is undefined`

**Comment by dereklieu** [comment]
@mhdomo yeah there are a couple of open tickets in this repo relating to uploading images. I haven't yet had a chance to look into this issue myself. If you've got time and the know-how, prose is looking for contributors to address this issue and others :+1:

**Comment by mhdomo** [comment]
I solved it by adding `prose`-configuration to Jekylls `_config.yml`.
