### ISSUE TITLE
Error while loading data from GitHub

### ISSUE THREAD

**Issue by rlshepard** [prose/prose#851]
I'm continuously getting this error as I try to update my site. Please advise. Thanks!

-Ryan

**Comment by dereklieu** [comment]
@rishepard What error are you getting, and what are the steps you take to re-create the error?

**Comment by dereklieu** [comment]
@rlshepard pinging you one more time. Will close if I don't hear back.

**Comment by gurusinga** [comment]
It happens to me right now as I revoked Prose from GitHub setting. @dereklieu
