### ISSUE TITLE
Error when saving: Invalid Request SHA

### ISSUE THREAD

**Issue by willmedtrainingsolutionscom** [prose/prose#853]
Please let me know what to do with this error:

![error](https://cloud.githubusercontent.com/assets/7152182/9000001/9d392036-370f-11e5-9aab-c39c24facff3.png)

Also, @ project team, please unblock my other account @fulldecent

**Comment by phillipadsmith** [comment]
@willmedtrainingsolutionscom Can you provide some more details on what's happening per the [contribution guidelines](https://github.com/prose/prose/blob/master/CONTRIBUTING.md) ?

Does this happen if you log out of Prose, then log back in?

Phillip.

**Comment by willmedtrainingsolutionscom** [comment]
Logging and and then in fixed the problem. Sorry, I should have tried this first! I do also realize that some of the meta data was missing the first time this was submitted, but not sure if that is related to the error. Closing now.

**Comment by phillipadsmith** [comment]
:+1:
