### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by phillipadsmith** [prose/prose#856]
Howdy,

I've got Prose running locally so that I can try to help out a bit.

When I run the existing tests in Chrome (44.0.2403.107), I am getting three test failures:

![prose-test-failures-aug-2-15](https://cloud.githubusercontent.com/assets/34128/9028073/7deab096-3921-11e5-9962-c7f08894830b.png)

Before I dig in further, I'm wondering if these failures are known and already being investigated?

Many thanks in advance,

Phillip.

**Comment by phillipadsmith** [comment]
CC @dereklieu

**Comment by tomsabin** [comment]
@phillipadsmith I get the same two failures for "Metadata editor view" but not for `includeTag`.

![screen shot 2015-08-03 at 15 15 16](https://cloud.githubusercontent.com/assets/885223/9039322/85c4fdfe-39f2-11e5-9578-bceaf7882eaf.png)

**Comment by dereklieu** [comment]
@phillipadsmith The two metadata tests are my responsibility, they show failing functionality that I haven't had time to write a patch for yet. I'm also not coming across the liquid tag issue.

**Comment by phillipadsmith** [comment]
> The two metadata tests are my responsibility, they show failing functionality that I haven't had time to write a patch for yet. 

Makes total sense. Is there an easy way to mark those tests as TODO @dereklieu ?

> I'm also not coming across the liquid tag issue.

Very odd. I'll dig a little bit... but obviously low priority if it's just happening for me.

Thanks @tomsabin @dereklieu! :+1: 

Phillip.

**Comment by dereklieu** [comment]
@phillipadsmith that would be a good idea, to mark todo tests. Let me know if you come up with anything on the liquid tags issue.

**Comment by phillipadsmith** [comment]
@dereklieu Can you assign this issue to me?

**Comment by dereklieu** [comment]
Fixed in #856 and #862
