### ISSUE TITLE
Jekyll repo of Oraganization is treated as project only

### ISSUE THREAD

**Issue by shubhajeet** [prose/prose#863]
Although repo is a Jekyll site . It is not being treated as Jekyll site. It may be due to shared. 
[Here is the link of the repo](https://github.com/Omegaalumni/Omegaalumni.github.io/)

**Comment by phillipadsmith** [comment]
@shubhajeet The repo works for me (see screenshot). What are you seeing / expecting to happen?

<img width="1039" alt="omegaalumni_github_io_ _prose" src="https://cloud.githubusercontent.com/assets/34128/9153230/961850f6-3dfe-11e5-9718-6180bb3536ca.png">

**Comment by shubhajeet** [comment]
@phillipadsmith 
Here is the dashboard
![screenshot from 2015-08-10 05 15 40](https://cloud.githubusercontent.com/assets/6178529/9157486/2023f5fe-3f1f-11e5-9ea1-8d895f4c6e29.png)

Omegaalumni.github.io does not have **view site** option like others.

**Comment by phillipadsmith** [comment]
@shubhajeet No Prose magic there my friend. You just need to add a "Website" field to your Github repo to get the "View site" link. 

<img width="931" alt="phillipadsmith_omegaalumni_github_io" src="https://cloud.githubusercontent.com/assets/34128/9157752/4e2a5616-3ebe-11e5-9fe5-73bd2196f8c3.png">

<img width="748" alt="phillipadsmith_ _prose" src="https://cloud.githubusercontent.com/assets/34128/9157754/60443ce0-3ebe-11e5-94b1-dd145160f998.png">

**Comment by phillipadsmith** [comment]
@shubhajeet If that answers the question, please close the ticket. :)
