### ISSUE TITLE
Should Prose be an official part of the Jekyll project?

### ISSUE THREAD

**Issue by erlend-sh** [prose/prose#866]
It's lovely to see Prose picking up some steam again in #743. Major kudos to you guys!

Seemingly [lost in the midst](https://github.com/prose/prose/issues/743#issuecomment-112825569) of the discussion, @daveaseeman asked @parkr & co a question that I think ought to be echoed:

> has anyone considered transferring the ownership of Prose to Jekyllrb?
> 
> I think most people could agree that a CMS like solution for Jekyll is useful. Perhaps an official association would make it easier to find maintainers.

I wholeheartedly agree. With Prose as an official Jekyll project:

- Prose could get exposure in docs.jekyllrb.com
- Prose would be a more natural subject on talk.jekyllrb.com (provided the new maintainers drop by occasionally)
- Jekyll gets a canonical front-end extension.

I sincerely hope the original & new maintainers as well as the Jekyll org would be amenable to such a transfer.

**Comment by daveaseeman** [comment]
@erlend-sh thanks for picking up on the comment and submitting it as an issue. I definitely don't have the experience to say this is a great idea, but as an avid user of jekyll & prose, and seeing prose as the predominant CMS-like solution for jekyll, it seemed intuitively like it might work out for the best!

What do you guys and gals think?

**Comment by phillipadsmith** [comment]
I'm all for the idea in theory, and assuming the Jekyll project wanted to adopt it. 

And, at the same time -- playing devil's advocate -- I wonder what the impact of being an "official" project of Jekyll would have on other current or future "Editor for Jekyll" projects?

It's unlikely that Prose will ever be all things to all people, and there at least a couple of competitive products to Prose. Having more editors for Jekyll -- even closed-source ones -- strikes me as a "good thing(tm)." So, I wonder about the impact of Jekyll having an "official" editor.

The main question for the Jekyll project is: does having an editor that works for less-technical people actually solve a problem they're experiencing? And, if so, is Prose the right solution to that problem?

**Comment by Leeds-eBooks** [comment]
Hello, lurker here (and possible contributor in a few weeks when I get some time!). I'm interested by your mention of competitors to prose, @phillipadsmith. Which are you thinking of? I have been completely unable to find any that come close to the ease of use of prose, buggy though it can occasionally be. If there are competitors with other features, I guess it could be useful for maintainers of prose to be aware of them.

**Comment by phillipadsmith** [comment]
Hey there @Leeds-eBooks: There's a great repository / list by @aharris88 of [Services for static sites here](https://github.com/aharris88/services-for-static-websites#online-editors-for-static-sites). It includes a list of several alternate editors for Jekyll.

HTH,

Phillip.

**Comment by colophonemes** [comment]
Hi all! 

I too am really excited that Prose is picking up steam, and I think that this would be fine in theory, assuming that those in the Jekyll project who took the project on were happy to keep it fairly platform-agnostic. At the moment, Prose is a great editor that (aside from a couple of quirks, like the handling of image URLs) can be used for pretty much any MD-based static site generator. It'd be a shame if the broader static site community lost out because functionality was developed with only one generator in mind.

**Comment by phillipadsmith** [comment]
>  can be used for pretty much any MD-based static site generator.

_Other_ static site generators...? **Blasphemy!**

![Burn the witch!](http://i.giphy.com/kPMwTWvKadCG4.gif)

**Comment by colophonemes** [comment]
![](http://gph.is/1iHLBRj)

**Comment by Leeds-eBooks** [comment]
@phillipadsmith Thanks for that! I've just gone through them all and I'm happy to say that prose wins out by a substantial margin. [The GitHub flow](https://help.github.com/articles/github-flow-in-the-browser/) comes close, but is not as easy for non-devs to get their head around. [KISS my BLOG](https://kissmyblog.com/) is probably the closest, but it doesn't seem to integrate with Jekyll easily (at least it didn't recognize my jekyll repo as a blog when I signed in). [Potion](https://github.com/captn3m0/potion) looked very similar to prose but it hasn't been committed to for 2 years and still has language like "When Potion will be complete, it will boast of the following features" in the readme, so pretty sure that's abandonware.

So apart from cloudcannon, which is a paid service, I don't think there is any real competition in prose's particular space.

**Comment by erlend-sh** [comment]
> So apart from cloudcannon, which is a paid service, I don't think there is any real competition in prose's particular space.

Well, @biiilmann & co from Netlify are apparently [working on some kind of visual editor](https://talk.jekyllrb.com/t/visual-editor-for-jekyll/1055/19?u=erlend_sh) which will be fully open source. I'm definitely excited to see what they've come up with.

**Comment by biilmann** [comment]
We're indeed working on a CMS for static site generators at [netlify](https://www.netlify.com) that'll be fully open-source.

The repository is private right now while we're working on getting the whole flow for getting up and running easy enough that we feel we won't scare off a bunch of normal users right away, but I'll be happy to invite anybody from the Prose community. Just shoot me a mail at matt@netlify.com with your Github username.

Our approach is to do one CMS that supports lots of static gens. We're seeing many of them in action at netlify and also run staticgen.com, so we're pretty well positioned to do something with the right set of abstractions to be easily adaptable to most of them.

Just like Prose it can work with the Github API, but we also have a small server you can run locally to use it directly against any Git repository, without depending on users having Github access (this will also allow for more fine-grained access control than the Github API allows, in the future). 

The plan is to open the repo within the next couple of weeks, but happy to give Prose users and contributors early access!

**Comment by rcross** [comment]
:+1:

**Comment by ianhobbs** [comment]
No. 
Clearly there a rich community of parallel developments with important differences in approaches. So Jekyll should support this community as a field of endeavour, rather than choose a solitary (leading!) example.

**Comment by parkr** [comment]
Going to close this out – I don't think Prose should merge with Jekyll so as a representative from Jekyll, "thanks! but no thanks! <3"

Keep doing crazy awesome things, you lovely people.

**Comment by phillipadsmith** [comment]
:+1:
