### ISSUE TITLE
Customizability

### ISSUE THREAD

**Issue by RaghuAllTheTime** [prose/prose#867]
Can you make prose dark, or change its font?
If so, how?
Or else, I would like such a feature.

**Comment by dereklieu** [comment]
@prose/contributors anyone want to work on prose skins?

**Comment by phillipadsmith** [comment]
@dereklieu I'm keen to add a "dark" skin akin to what Penflip has. If you can get me added to the @prose/contributors list, you can assign this to me.

**Comment by RaghuAllTheTime** [comment]
@dereklieu  I _Could_ add fonts, with Source Code Pro as the default, and  allow the user to add a custom font.

**Comment by tristen** [comment]
:-1: on this. Prose should be simple. Adding _skins_ introduces complexity, bloat and I'd argue is completely unnecessary.

There's nothing stopping someone from forking prose and altering the stylesheet for their own purposes. Please let's make incremental improvements to the existing aesthetic.

**Comment by RaghuAllTheTime** [comment]
No I just want a dark background for the editor, if possible.
Please tell me you can just make the editor dark, and a simple kind of dark, eg: the editor in [medium.com](Medium.)

**Comment by dereklieu** [comment]
@tristen point taken. Closing this as it's not a priority right now.

**Comment by tristen** [comment]
@RaghuAllTheTime I totally recommend [Stylish](https://chrome.google.com/webstore/detail/stylish/fjnbnpbmkenffdnngjfgmeleoegfcffe?hl=en) - a chrome extension for creating custom skins if you want a dark theme for your own needs.
