### ISSUE TITLE
Title input form updates title metadata in markdown files

### ISSUE THREAD

**Issue by dereklieu** [prose/prose#868]
In #862 I removed the [metadata-value setter function call](https://github.com/prose/prose/commit/f7d0e12461769e2e6a3c8c71d986552242c28ce3) in `views/file#makeDirty`, aka the way you inform the editor that something has happened that might warrant a save.

This separates some concerns; if `metadata.js` is responsible for all the meta forms, and these correspond to `model.metadata`, then `file.js` shouldn't be the thing that saves to `model.metadata`. 

However, I didn't realize that `header.js#updateTitle` [relies on the makeDirty function](https://github.com/prose/prose/blob/705b0cf056a967e570fd0c4d2eb9bc4770b79da4/app/views/header.js#L92) to set title metadata.

So this is a regression. I propose that `header.js` should be responsible for setting title metadata in these cases, just like `toolbar.js` [sets the publish/unpublish meta value](https://github.com/prose/prose/blob/705b0cf056a967e570fd0c4d2eb9bc4770b79da4/app/views/toolbar.js#L358-L360). This would keep `metadata.js` from having to do stuff like [this](https://github.com/prose/prose/blob/705b0cf056a967e570fd0c4d2eb9bc4770b79da4/app/views/metadata.js#L262-L275) to figure out the value of form elements it's not responsible for.

**Comment by dereklieu** [comment]
Related to #854

**Comment by phillipadsmith** [comment]
> So this is a regression. I propose that header.js should be responsible for setting title metadata in these cases, just like toolbar.js sets the publish/unpublish meta value. This would keep metadata.js from having to do stuff like this to figure out the value of form elements it's not responsible for.

:+1:

**Comment by giladju** [comment]
not sure this is directly related - but I'm not seeing the Metadata (& settings) button on the right anymore
this is strange as other github users on the same repo are able to enter metadata

**Comment by dereklieu** [comment]
@giladju these changes aren't deployed to prose.io yet so this may be another issue, or something to do with your metadata settings.
