### ISSUE TITLE
Allow access to certain repositories only

### ISSUE THREAD

**Issue by techtonik** [prose/prose#872]
Prose request access to all repositories under my account. Is it possible to isolate the changes to one repository only?

**Comment by phillipadsmith** [comment]
@techtonik As far as I can tell from the [Github API docs on 'scopes'](https://developer.github.com/v3/oauth/#scopes), it wouldn't be possible to do this during the Github authorization step.

**Comment by techtonik** [comment]
@phillipadsmith how about [personal access tokens](https://github.com/settings/tokens) - can they be used?

**Comment by dereklieu** [comment]
@techtonik Unfortunately no. Prose supports access to all repos, or access to only public repos. This is a limitation of the Github API, personal access tokens or no.

If you wanted to limit Prose to seeing one repo, the best thing to do would be to create a new Github account and fork just that one repo.
