### ISSUE TITLE
Config only allows one hidden element since `metadata.js` refactor

### ISSUE THREAD

**Issue by tomsabin** [prose/prose#877]
With a config file that has multiple hidden fields, only the last hidden element is rendered in the front matter. From my understanding this was introduced in 0060a9fd2d85790749eb225e4d7be07b4f918c16 (10th August):

in [`app/views/metadata.js:147`](https://github.com/prose/prose/blob/master/app/views/metadata.js#L147), the model's `metadata` is being rewritten multiple times (depending on how many hidden elements you have), but not actually extending the hash correctly. This is because the variable `metadata` has been assigned to `this.model.get('metadata')` before iterating over the YML config begins.

Changing line 147 from:

```JS
this.model.set('metadata', _.extend(newMeta, metadata));
```

to:

```JS
this.model.set('metadata', _.extend(newMeta, this.model.get('metadata')));
```

ensures that each time in the iteration we are always getting the latest metadata.

**Comment by dereklieu** [comment]
@tomsabin point taken, would love a PR and test of this behavior.

**Comment by tomsabin** [comment]
@dereklieu, certainly - I'm working on that now

**Comment by tomsabin** [comment]
@dereklieu please see https://github.com/prose/prose/pull/878
