### ISSUE TITLE
Wrong label on for select box on load

### ISSUE THREAD

**Issue by mushishi78** [prose/prose#882]
When you have separate values and labels for a select box in the metadata, it fails to load the correct label for the box from the value already in the metadata.

Edit: Actually it doesn't matter whether you use a label or not, it just flat out doesn't load the current value in the metadata at all.

**Comment by dereklieu** [comment]
Confirmed this behavior. The [docs](https://github.com/prose/prose/wiki/Prose-Configuration#select--multiselect) don't say anything about setting a default `value` which makes me think this was never a feature anyway, but I think it'd be a nice to have.

**Comment by dereklieu** [comment]
Nope, I was wrong, this is a bug in which the default select value doesn't get chosen.
