### ISSUE TITLE
Should preview show me the full layout or just the markdown?

### ISSUE THREAD

**Issue by nasht00** [prose/prose#902]
I'm playing around with prose.

I have a Jekyll site, it allows me to edit the markdown files, and the preview shows me the generated html from the markdown.

However, is it supposed to also show me the rest of the page when I preview? Like the layout? CSS? etc?

My site uses Jekyll 3 and plugins, if it matters...

**Comment by nicolasmccurdy** [comment]
It just shows you your rendered markdown content, without the extra templates or styles in your Jekyll site.

**Comment by nasht00** [comment]
From the Prose website (emphasis mine):

> Prose has advanced support for Jekyll sites and markdown content. Prose detects markdown posts in Jekyll sites and provides syntax highlighting, a formatting toolbar, and draft previews **in the site's full layout**.

**Comment by aussielunix** [comment]
@nasht00 
I have got this working by adding the following to `_config.yml`
`siteurl: ...Turns on Jekyll live previews. The url is the homepage of the live site.`

```
prose:
  siteurl: 'http://foo.example.com'
...
...
```

**Comment by dereklieu** [comment]
@nasht00 @aussielunix I don't have a repo I can test this with right now, but please mark this closed if it's resolved or send an update here.

**Comment by blairanderson** [comment]
@dereklieu confirming, this works with markdown files if you add the prose config object with a url.

It does not work with `.html` files but i think we should make a separate issue for that

**Comment by blairanderson** [comment]
@nasht00 more info can be found here https://github.com/prose/prose/wiki/Prose-Configuration#options

**Comment by joshcomley** [comment]
I don't seem to have luck with this on my blog I'm setting up:

<https://github.com/joshcomley/Overengineer>

I've just taken a template and I'm currently in the process of configuring it all.

I put the right entry in _config.yml but nevertheless, when I click on the preview button I just get the standard preview. Is there something I might be missing?

Here is my `_config.yml`:

<https://github.com/joshcomley/Overengineer/blob/gh-pages/_config.yml>

**Comment by joshcomley** [comment]
Note to self, here:

Prose.io uses the `blog.html` template in `\_layouts`, if you don't have this, then you'll just get a blank preview.

However, I still haven't solved why the previews weren't working. I have taken a copy of the Prose starter site, replaced my entire repository with it, then previews worked. Then I gradually put my old repo code back in bit by bit, testing at each increment, and now it's restored fully again but previews are working.

**Comment by joshcomley** [comment]
OK, further research yields this:

The `_config.yml` file needs to have this exact (as far as I can tell) setting in it:

	prose:
		metadata:
		  _posts:
			- name: "layout"
			  field:
				element: "hidden"
				value: "blog"

I tried setting `blog` to `default`, where I do have a `default.html` in my `_layouts` folder that is identical to the `blog.html`, but it would disable the live preview.
