### ISSUE TITLE
prose.io is putting empty image strings in to the html

### ISSUE THREAD

**Issue by kategenevieve** [prose/prose#903]
Hi,
Coming up against a significant problem on our website build - prose.io is mistakenly putting empty image strings in to the html. Not sure whether it should just not be adding the empty image paths at the CMS level, or whether it should be getting to the {% if %} statements in the _includes/media.html. Tests show that the if statements set up in the media.html are not working.

Trying to fix this by -
* manually deleting the superfluous entries in github after each edit (which is a arduous!)
* creating a 1x1pixel image and let it add that instead of just breaking
But they are bodgey solutions & waste time.

Any ideas how to fix this bug? The site is www.chroma.space

**Comment by dereklieu** [comment]
Hey @kategenevieve, can you explain the steps I might take to reproduce your bug? Does prose add extra image strings every time you save, or only some of the time? What does your _includes/media.html file look like?

**Comment by kategenevieve** [comment]
Thanks

To reproduce - edit and save any of the .mk or .markdown files
in /_posts/projects/. This adds a faulty path for the jpg image, png image
and panorama image metadata fields to the html.

This occurs every time.

media.html file attached.

CCing in Dan who is helping me with the website & who is more knowledgable
than me :)

Look forward to hearing it back

Kate

**Comment by kategenevieve** [comment]
Hey Kate and Derek,

Any update on this? It'd be great to know why the {%if} statements are
failing to check things properly. I'd like to get the broken bits fixed
over the weekend if possible!

Cheers,
Dan

**Comment by kategenevieve** [comment]
Hey Derek,

Can you confirm you got the media.html file to your
derek@developmentseed.org email last week? Have you had any luck with
figuring out the {if} problem if so?

Cheers,
Dan

**Comment by kategenevieve** [comment]
Hi Derek,
It would be great to hear back about this as I would love to fix the
website for the Christmas newsletter. It has worrying black banners at
present :)

Kate

On Tue, Dec 15, 2015 at 9:55 AM, dan bibby <weatherbrow@gmail.com> wrote:

> Hey Derek,
>
> Can you confirm you got the media.html file to your
> derek@developmentseed.org email last week? Have you had any luck with
> figuring out the {if} problem if so?
>
> Cheers,
> Dan
>
> On Fri, Dec 4, 2015 at 12:59 PM, dan bibby <weatherbrow@gmail.com> wrote:
>
>> Hey Kate and Derek,
>>
>> Any update on this? It'd be great to know why the {%if} statements are
>> failing to check things properly. I'd like to get the broken bits fixed
>> over the weekend if possible!
>>
>> Cheers,
>> Dan
>>
>> On Sun, Nov 29, 2015 at 4:43 PM, Kate Genevieve <kate@chroma.space>
>> wrote:
>>
>>> Thanks
>>>
>>> To reproduce - edit and save any of the .mk or .markdown files
>>> in /_posts/projects/. This adds a faulty path for the jpg image, png
>>> image and panorama image metadata fields to the html.
>>>
>>> This occurs every time.
>>>
>>> media.html file attached.
>>>
>>> CCing in Dan who is helping me with the website & who is more
>>> knowledgable than me :)
>>>
>>> Look forward to hearing it back
>>>
>>> Kate
>>>
>>>
>>> On Sat, 28 Nov 2015 at 17:20 Derek Lieu <notifications@github.com>
>>> wrote:
>>>
>>>> Hey @kategenevieve <https://github.com/kategenevieve>, can you explain
>>>> the steps I might take to reproduce your bug? Does prose add extra image
>>>> strings every time you save, or only some of the time? What does your
>>>> _includes/media.html file look like?
>>>>
>>>> —
>>>> Reply to this email directly or view it on GitHub
>>>> <https://github.com/prose/prose/issues/903#issuecomment-160321862>.
>>>>
>>>
>>
>


-- 
Kate Genevieve
chroma.space

m: 07747725588
@kategenevieve

**Comment by dereklieu** [comment]
Hi all, I've received your emails but haven't had time to look yet. I'll
try to get to it before the end of the week.

**Comment by kategenevieve** [comment]
Thank you, Derek

On Tue, Dec 15, 2015 at 6:21 PM, Derek Lieu <notifications@github.com>
wrote:

> Hi all, I've received your emails but haven't had time to look yet. I'll
> try to get to it before the end of the week.
>
> On Tue, Dec 15, 2015 at 4:58 AM, kategenevieve <notifications@github.com>
> wrote:
>
>
> > Hi Derek,
> > It would be great to hear back about this as I would love to fix the
> > website for the Christmas newsletter. It has worrying black banners at
> > present :)
> >
> > Kate
> >
> >
> > On Tue, Dec 15, 2015 at 9:55 AM, dan bibby <weatherbrow@gmail.com>
> wrote:
> >
> > > Hey Derek,
> > >
> > > Can you confirm you got the media.html file to your
> > > derek@developmentseed.org email last week? Have you had any luck with
> > > figuring out the {if} problem if so?
> > >
> > > Cheers,
> > > Dan
> > >
> > > On Fri, Dec 4, 2015 at 12:59 PM, dan bibby <weatherbrow@gmail.com>
> > wrote:
> > >
> > >> Hey Kate and Derek,
> > >>
> > >> Any update on this? It'd be great to know why the {%if} statements are
> > >> failing to check things properly. I'd like to get the broken bits
> fixed
> > >> over the weekend if possible!
> > >>
> > >> Cheers,
> > >> Dan
> > >>
> > >> On Sun, Nov 29, 2015 at 4:43 PM, Kate Genevieve <kate@chroma.space>
> > >> wrote:
> > >>
> > >>> Thanks
> > >>>
> > >>> To reproduce - edit and save any of the .mk or .markdown files
> > >>> in /_posts/projects/. This adds a faulty path for the jpg image, png
> > >>> image and panorama image metadata fields to the html.
> > >>>
> > >>> This occurs every time.
> > >>>
> > >>> media.html file attached.
> > >>>
> > >>> CCing in Dan who is helping me with the website & who is more
> > >>> knowledgable than me :)
> > >>>
> > >>> Look forward to hearing it back
> > >>>
> > >>> Kate
> > >>>
> > >>>
> > >>> On Sat, 28 Nov 2015 at 17:20 Derek Lieu <notifications@github.com>
> > >>> wrote:
> > >>>
> > >>>> Hey @kategenevieve <https://github.com/kategenevieve>, can you
> > explain
> > >>>> the steps I might take to reproduce your bug? Does prose add extra
> > image
> > >>>> strings every time you save, or only some of the time? What does
> your
> > >>>> _includes/media.html file look like?
> > >>>>
> > >>>> —
> > >>>> Reply to this email directly or view it on GitHub
> > >>>> <https://github.com/prose/prose/issues/903#issuecomment-160321862>.
> > >>>>
> > >>>
> > >>
> > >
> >
> >
> > --
> > Kate Genevieve
> > chroma.space
> >
> > m: 07747725588
> > @kategenevieve
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/prose/prose/issues/903#issuecomment-164707752>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/prose/prose/issues/903#issuecomment-164846511>.
>



-- 
Kate Genevieve
chroma.space

m: 07747725588
@kategenevieve

**Comment by dereklieu** [comment]
If a metadata value didn't exist in frontmatter before and:

1. You open the file in prose;
2. You don't enter anything for that metadata key but save other changes;

Prose will insert a metadata value that is an empty string, or possibly an empty array for multi-selects.

This is not a great side-effect, but jekyll templates should do conditional checking anyway and `""` evaluates to false. 

```
{% if post.METADATA_KEY %}
> something
{% endif %}
```

If the metadata field is a multiselect (array) you'll probably need to do [other stuff](https://github.com/jekyll/jekyll/issues/2538).
