### ISSUE TITLE
Split Screen Markdown edit

### ISSUE THREAD

**Issue by windweller** [prose/prose#905]
Hi! I'm wondering if you guys have considered to offer a split screen markdown edit?
Right now the "preview" seems fine...but a split screen simultaneous edit seems more useful!

I'm just wondering if this is a technical difficulty or a design choice...

**Comment by dereklieu** [comment]
This would be cool but I'm not sure there's any bandwidth for this sort of undertaking right now. Right now maintenance is the priority, so unfortunately I have to mark this closed - although not from lack of interest, just time!

PS. http://socrates.io/ does this pretty well already and I use it a ton for collaborative editing.
