### ISSUE TITLE
page doens't load if it contains an iframe

### ISSUE THREAD

**Issue by frob** [prose/prose#909]
I was writing an article locally, and when I attempted to open this article on prose.io it didn't load completely. My assumption is that this is because it has an iframe youtube embed in it. I have not investigated further.

**Comment by dereklieu** [comment]
Hey @frob I tried recreating these steps but was able to open a markdown file with an embed in it. 

Do you have any other clues as to what might be happening? Does prose show you any error messages, or does it just stick on the loading indicator? Any output to console? Do other files load ok?

**Comment by frob** [comment]
maybe it was a connection issue, I will try again.

**Comment by frob** [comment]
It seems the issue has resolved itself. I can no longer reproduce.

**Comment by dereklieu** [comment]
:+1:
