### ISSUE TITLE
Saving a .md file adds line break top of file every time

### ISSUE THREAD

**Issue by timwis** [prose/prose#916]
Steps to reproduce:
1. Create a new `.md` file, notice the default text has the title on the first line
2. Hit save, commit
3. Refresh and notice there is a blank line above the title
4. Hit save again, commit
5. Refresh and there's another line. Repeat.

I've been doing this with a fork of prose/starter on the live prose.io site, which has metadata on it.

**Comment by dereklieu** [comment]
@timwis Yeah, I've noticed this too and it's super annoying.

**Comment by brontosaurusrex** [comment]
Noticed that as well.

**Comment by timwis** [comment]
Looks like it's working, submitted a pull request #919 for review
