### ISSUE TITLE
Npm run test command not working as expected

### ISSUE THREAD

**Issue by dereklieu** [prose/prose#925]
In node 4.0, running `npm test` is no longer printing test results to console. Seems to just hang there. 

Probably related to [mocha-phantom moving core to a different module](https://github.com/nathanboktae/mocha-phantomjs) after 4.0.

This would be a good reason to upgrade the node version we're pegging this to.

**Comment by jmatsushita** [comment]
Hi there @dereklieu 

I was looking at how things are with regards to testing in Prose given that you mentioned needing more tests to do regression testing on some cool PRs (like the ProseMirror integration #935 )

I came by this issue and couldn't reproduce it locally switching with nvm to node 4.0, 4.1 or 4.2. I thought I'd give a shot at building with travis across all know node_js version to see if it caught something but it seems sane and [passes and displays test results to the console except on 0.6 and 0.8](https://travis-ci.org/iilab/prose/builds/116680548).

Cheers,

Jun

**Comment by dereklieu** [comment]
@jmatsushita you're right, I just did a fresh `npm install` on `4.2.4` and it worked fine. Closing this.
