### ISSUE TITLE
Error thrown: defaults.filter is not a function

### ISSUE THREAD

**Issue by jasonlally** [prose/prose#931]
In chrome Version 48.0.2564.116 m I'm getting the following error when I load a specific markdown file for editing. In the debugger, I can see that defaults is populated with an array of objects, but defaults.filter then doesn't work.  I get the same error in Firefox 44.0.2.

I'm on Windows 7

![error](https://cloud.githubusercontent.com/assets/534176/13333558/761f138c-dbbc-11e5-9cdc-139e99e935d3.PNG)

**Comment by jasonlally** [comment]
Hey, nevermind on this. It was an issue with the underlying config that I couldn't see. I must have stared at that forever, but I got it working :smile:

**Comment by dereklieu** [comment]
@jasonlally :+1: was it an issue with your metadata settings, just out of curiosity?

**Comment by jasonlally** [comment]
Yes, I had defined the metadata for one of the post types as:

```
postfolder:
  _posts:
```

When I switched to 
```
postfolder\_posts
```

Things worked.
