### ISSUE TITLE
Entities in metadata text fields being double-escaped

### ISSUE THREAD

**Issue by tfe** [prose/prose#937]
I've got some text fields configured for the post metadata to add e.g. title, description. I'm seeing an issue where prose is replacing some characters with their HTML entities upon editing, but it doesn't seem to be undoing that later resulting in double- and triple-encoded entities.

A concrete example:

When starting out, I have this in the text field:

![screen shot 2016-03-23 at 1 46 42 pm](https://cloud.githubusercontent.com/assets/21501/14000307/f5b15956-f0fd-11e5-90fd-5252a39159c8.png)

The apostrophe in "we're" is a standard apostrophe char, nothing fancy. When I save this, I get this in the actual source file, as expected:

![screen shot 2016-03-23 at 1 49 16 pm](https://cloud.githubusercontent.com/assets/21501/14000350/1ac314b4-f0fe-11e5-9336-957064b31cee.png)

If I edit again though, this is what I see in the editor. The entity is the HTML entity for a standard apostrophe:

![screen shot 2016-03-23 at 1 51 05 pm](https://cloud.githubusercontent.com/assets/21501/14000406/5d742244-f0fe-11e5-9d54-8289568737fd.png)

And this is what is saved in the source file:

![screen shot 2016-03-23 at 1 52 45 pm](https://cloud.githubusercontent.com/assets/21501/14000468/95644e04-f0fe-11e5-883b-53d20a3cd58a.png)

The third time, the ampersand gets replaced with its entity, and this continues recursively forever on each edit:

![screen shot 2016-03-23 at 1 53 45 pm](https://cloud.githubusercontent.com/assets/21501/14000499/b88678e4-f0fe-11e5-936b-9d5110f406bf.png)

![screen shot 2016-03-23 at 1 53 59 pm](https://cloud.githubusercontent.com/assets/21501/14000504/bacd41aa-f0fe-11e5-97e7-4f09136ab34e.png)

I looked through the open and closed issues but it seems no one else is encountering this, which seems strange because I'd think it would be a super-common issue if it were happening to everybody.

It's happening on totally stock OS X with latest Safari.

**Comment by dereklieu** [comment]
@tfe yeah I've noticed this before as well. It's possible this is a regression of an XSS-related issue from a while back. I think a bit more sensible escaping could go a long way here.

**Comment by andrew-luminal** [comment]
I've been having this issue as well. Was debugging and realized that this could be fixed by changing this line:
https://github.com/prose/prose/blob/f8092a72b00be8065a29498d309c3f843fb14a3a/app/views/meta/textarea.js#L84

...to NOT call `_.escape`. Should I make a PR?

**Comment by dereklieu** [comment]
@andrew-luminal Ah, I put that line in there in #799. If we can not escape there and not get pwned then that should be fine.

**Comment by andrew-luminal** [comment]
@dereklieu Awesome, thx -- we're actually doing manual corrections at this for my company's blog at the moment so I'm hoping this gets fixed soon. Any way I can help get it pushed through?

**Comment by dereklieu** [comment]
@andrew-luminal I can spend some time testing this tonight. There's a repo from that ticket I linked to which makes it super convenient to know where an xss attack can succeed. If I don't encounter anything drastic then I will push a change with your suggestion.
