### ISSUE TITLE
Decouple CSS

### ISSUE THREAD

**Issue by dereklieu** [prose/prose#940]
Introduce a gulp build step to the CSS file and split it into parts, so it's not one monolith. Would make it less of a headache to update vendor styles which are just built-in right now. cc #938

**Comment by edrex** [comment]
Oh so, the Codemirror styles are manually inlined in /styles.css currently? I somehow thought there was a concat step in the gulp file. 

Maybe use something with @import walking, so the script doesn't have to hard code all the source files? I frequently use LESS or SCSS, but also understand some folks consider them overkill. 

A minimal option with room to grow might be https://github.com/postcss/postcss-import, which would open up using autoprefixer etc (also a postcss plugin). This would probably be my recommendation.

**Comment by edrex** [comment]
I'd be up for taking this on, if you don't already have WIP @dereklieu.

**Comment by dereklieu** [comment]
@edrex yeah the old Codemirror had a `position: absolute` inlined for this particular gutter, the new one ships with that style applied via css.

I have a WIP that uses SCSS and gulp-sass that is pretty much done, however I ran into a few hiccups regarding (I think) paths for custom fonts. Happy to push it up if you'd like to take a look at fixing the last few steps.

**Comment by edrex** [comment]
Sure, I can take a look. Building on the codemirror-tests branch, or independent?

**Comment by dereklieu** [comment]
@edrex thanks! I put them on a separate branch [here](https://github.com/prose/prose/tree/decouple-css). 

The gulp tasks just replace the version of `style.css` that's in the directory root. That felt easier than putting the newly parsed css file into `dist` b/c of icon/font pathing. So right now the old `style.css` is left as is for the sake of debugging, but as soon as you run `gulp build` or `gulp css` it'll replace it, pulling in newer Codemirror css.

I didn't look too far after getting here but noticed that the font in the code editor (for .yml files, etc) looked different, so figured it was either paths or newly missing classes/CSS. Let me know what you find here. Thanks again.

**Comment by edrex** [comment]
I notice the editor width at different window widths is different from prose.io, but it seems to be the same as master branch. I assume that's a recent, undeployed change?

**Comment by edrex** [comment]
Are the font discrepancies you're seeing in Firefox? I see them there. That's usually because of differences in handling of WOFF fonts (Firefox often chokes if the server doesn't set the right MIME header).

**Comment by dereklieu** [comment]
@edrex yeah the width is a recent change. It hasn't yet been deployed on prose.io though.
