### ISSUE TITLE
JSON incorrectly checking parts where prose has added blank values for image files

### ISSUE THREAD

**Issue by kategenevieve** [prose/prose#945]
Hello there
Still having a significant problem with the images at http://chroma.space/ as referenced here > https://github.com/prose/prose/issues/903#issuecomment-160321862 

When I update the written content of a page using prose.io "prose puts empty strings where it didn't find metadata before" @weatherbrow >> "The problem is caused by JSON incorrectly checking parts where prose has added blank values for image files." & the effect is that the images disappear...

The workaround was editing out random unwanted values in Github instead of prose.io. But this seems to cripple the CSS and default the page to HTML - see current Now page for example >> http://chroma.space/now/

Is there a better solution? About to start some serious website work and this problem throws a huge spanner in the works. 

thanks
Kate

**Comment by dereklieu** [comment]
Currently Prose inserts empty strings for metadata fields when it detects a falsy value. Would it break anyone's build if it removed those fields from the frontmatter instead?

**Comment by dereklieu** [comment]
@kategenevieve Prose no longer inserts empty strings when there is no value in the metadata, let me know if this fixes your build.
