### ISSUE TITLE
How do you use Prose on Github Enterprise?

### ISSUE THREAD

**Issue by aharris88** [prose/prose#946]
I see that there is an oauth.json file, but I'm not sure what I need to change. I know what to change site to, but I'm not sure about the api. Also, what is clientId and gatekeeperUrl? Is there something that I need to host on heroku to get this to work?

**Comment by dereklieu** [comment]
If it helps, this is [Gatekeeper](https://github.com/prose/gatekeeper)

Sorry, but I'm not too familiar with Github Enterprise. If it exposes the same API endpoints as github.com, then it should be straightforward. User authentication code is in the [models#User](https://github.com/prose/prose/blob/master/app/models/user.js#L21) and gets called from [boot](https://github.com/prose/prose/blob/master/app/boot.js#L49).

**Comment by aharris88** [comment]
Thanks. I didn't realize I needed a server... It would be great if there were detailed instructions on how to setup Prose for Github Enterprise.

**Comment by dereklieu** [comment]
@aharris88 I've started a [docs file](https://github.com/prose/prose/blob/master/DEPLOYMENT.md) to start capturing some of this stuff, and to make it easier to deploy your own version. What else is helpful to know vis a vis setting up Prose for enterprise?

**Comment by dereklieu** [comment]
Closing this for lack of next actions. Happy to give advice on anyone who wants to set up prose in their own local hosting environment.

**Comment by joraff** [comment]
I worked on this today and am stuck configuring gatekeeper. 

After using the "temporary code" to authorize gatekeeer, what do you do with the access_token it gives you?

**Comment by joraff** [comment]
I think I went down the wrong rabbit hole with gatekeeper. I configured gatekeeper as the Oauth application's callback URL. Pretty sure the only place one needs to spec to gatekeeper is in oauth.json, correct?

**Comment by dereklieu** [comment]
@joraff On the prose side, yes, you should only have to modify `clientId` and `gateKeeperUrl`. In gatekeeper you'll have to modify config.json to match your credentials.

The way the access_token works is, it should get sent back to the Prose application as a url query ala `?access_token=1234`. Prose reads this on it's own and replaces it once it's finished with it in the url. Let me know if you have more questions here.

**Comment by joraff** [comment]
Figured it out, prose is not loading values from my oauth.json file. I hard coded the values in prose.js and it started working.

Trying to track down why that is right now - the file is definitely there.

**Comment by joraff** [comment]
Oh, just had to `gulp` again. I thought prose read oauth.json on the fly.
