### ISSUE TITLE
Colons in meta text fields

### ISSUE THREAD

**Issue by gesa** [prose/prose#965]
I've been searching for a place to try to fix this in either Prose or js-yaml but I think it's just a little too far over my head.

If I have a textarea or text field set up via the [prose configuration](https://github.com/prose/prose/wiki/Prose-Configuration), I expect to be able to enter _virtually_ any text into that field, and have it all treated as text. I've found, though, that if the text contains a colon, what i expected to be written as 

```yaml
text_field: "Lorem ipsum: dolor sit amet"
```

is instead written as

```yaml
text_area:
  Lorem ipsum: "dolor sit amet"
```

This is super frustrating, as my text fields frequently contain colons. One workaround is to enter the text in the field as `"Lorem ipsum: dolor sit amet"` to have it save properly, but on load the quotation marks are dropped and it attempts to save as a hash once again. (so the quotation marks have to be added every time the file is changed, even if that field is going untouched)

If anyone can point me in the right direction, I'll take a stab at making the fix. But my hunt is approaching wit's end. 😕

**Comment by dereklieu** [comment]
@gesa this is frustrating if you use semicolons a lot. I'm not running into it using basic text fields on prose.io, but I do see what you mean on text areas. I imagine if you're using a semicolon, then you're typing a lengthier block of text that might not fit in a text field.

Regarding text areas, I think this might be a mismatch of expectations. Prose treats text areas the same way it treats the raw editor, but in fact I think you'd use the text area to enter long pieces of text that might not fit in a text field. In that case, you would want to treat a text area like a super sized text field.

If that's the case, we'd just need to remove `jsyaml.safeLoad` from [here](https://github.com/prose/prose/blob/master/app/views/meta/textarea.js#L73) and make sure we escape appropriately.

**Comment by gesa** [comment]
@dereklieu thanks for pointing me in the right direction! I discovered in fact that if I stuff the contents of that field into a double-quoted string before loading through js-yaml, it maintains colons, as well as line breaks and markdown formatting ( 🎉 )

I'm having one problem though. There are two tests failing now, and I can't figure out why. (This is partially because I straight-up do not understand the test suite very well. Or test suites in general? I respect tests, I just haven't had a lot of opportunity to work with them.)

This one I can't figure out why it was written the way it was. I have to conclude there is an aspect of the functionality I simply do not grok "Metadata editor view setting defaults on load removes meta values that are empty strings from textarea fields".

The other, I guess I can't understand _how_ it works: "Metadata form elements Reading values does not endlessly escape text areas"

tbh i'm not even sure what I'm asking here. Is there somewhere I can dig in/start reading to get a better understanding of what's going on here?

**Comment by dereklieu** [comment]
@gesa not sure why those are failing but could very well be a problem with the way I wrote the tests. 

First one is to confirm that meta elements such as below are not included in frontmatter:

```(yaml)
value: null
value: ""
```

Second one is just to escape values, not sure why it's breaking but if you push your work I can help you troubleshoot the tests.
