### ISSUE TITLE
Using Prose when Jekyll is hosted on Firebase?

### ISSUE THREAD

**Issue by vilav** [prose/prose#967]
Hello

Jekyll noob here. Prose looks neat, clean UI! I intend to host my Jekyll blog on Firebase Hosting (announced at Google IO 2016). Any way I can use Prose with my Jekyll blog then? Self host it as a backend for my Jekyll blog?

Thanks

**Comment by dereklieu** [comment]
Hey, glad you like Prose and are considering using it. Currently Prose works with content hosted on Github, although I'm working on a Gitlab version. I'm not familiar with Firebase or what your set up will look like, but perhaps you could connect Github and Firebase using a service like [travis](https://travis-ci.org/).

And yes, you can self-host your own version of Prose, you just need to set up [gatekeeper](https://github.com/prose/gatekeeper) to handle oauth. If you want to modify Prose to accommodate a different API besides Github, then this would take a lot longer.

**Comment by vilav** [comment]
@dereklieu Thanks Derek! Pretty new to Jekyll (and developing for the web). I reckon smarter folks than I will have to figure this out. I did intend to use Travis for the exact same integration you suggested from Github to Firebase but that isn't well documented either, at the moment.

**Comment by dereklieu** [comment]
Hope this was helpful, if anyone has a pointer or specific issue regarding this please re-open.
