### ISSUE TITLE
Prose.io does not honor prose metadata in _config.yml  for private repositories

### ISSUE THREAD

**Issue by akshshar** [prose/prose#971]
Love the tool! In fact I'm using it extensively with my jekyll theme to create a blogging/publishing platform on github for my team.

However, I started using [jekyll-auth](https://github.com/benbalter/jekyll-auth) to be able to achieve the same level of collaboration, but with authentication against private github organizations for some of my websites for private documentation.

My workflow is simple. I get members to edit their content and publish in the master branch of the private repository using prose.io. I have webhooks deployed that automatically build and deploy the website with jekyll-auth on heroku. So It's equivalent to github-pages, but private.

Everything is working great, except prose.io does not take into consideration the prose field in my _config.yml file in the private repository.

To test it out, I made one of my private repositories public by moving it to a public organization and prose began to honor the prose metadata fields. 

Is this a known implementation detail that I should be aware of or a bug?

**Comment by dereklieu** [comment]
@akshshar thanks for opening this ticket. Sounds like a bug to me.

**Comment by akshshar** [comment]
Not a bug :).  Incidentally I had an extra `exclude:` in my _config.yml that Jekyll did not complain about. But I checked the network requests for prose.io on chrome and it clearly pointed out the mistake.

It's working really well and I have my private-blogging-website through heroku set up with prose.io.
We can close this issue, sorry for the trouble.

**Comment by dereklieu** [comment]
+1
