### ISSUE TITLE
Can't remove private repositories

### ISSUE THREAD

**Issue by chimit** [prose/prose#972]
First when I registered I used default settings and all my private repositories became visible in prose.io. How can I remove them?

I tried to remove OAuth keys and log in with public repositories only access, but got an error:
> 403 Forbidden
> You need at least read:org scope or user scope to list your organizations.

**Comment by dereklieu** [comment]
Wondering if this is a regression of #963

**Comment by dereklieu** [comment]
@chimit thanks for reporting this, you can now remove oauth keys, and log in with public repos only.
