### ISSUE TITLE
Error when trying to commit: remote ref is at X but expected Y

### ISSUE THREAD

**Issue by kaplas** [prose/prose#975]
I'm maintaining a small Jekyll installation for my fiancée at
https://github.com/niinapiira/neppari.net/
and she's using Prose to update its text content. Today, after some changes she made, Prose didn't allow her to commit changes anymore, but reported a git error instead:

<img width="303" alt="screen shot 2016-06-09 at 11 34 52" src="https://cloud.githubusercontent.com/assets/1321686/15923685/1a36efb8-2e37-11e6-9814-2961098a07b3.png">

Your contributing guidelines asked for JavaScript errors; well, there's HTTP 409 Conflicts, as one would expect:

<img width="455" alt="screen shot 2016-06-09 at 11 37 30" src="https://cloud.githubusercontent.com/assets/1321686/15923725/40c74e2a-2e37-11e6-92ec-2c333e508b15.png">

I do not know what kind of actions she took before the error started to appear, but based on what I've seen previously, I'd expect that there has been many commits for different pages in a short period of time. Anyway, something apparently made the local git repo (?) to go off-sync, or something.

So, this issue is

1. A request for someone to do something something quickly to fix the situation, so that she could continue on maintaining the site :)
2. A bug report

Browsers used: Latest Firefox on Windows 10 + latest Chrome on OS X.

Thanx for all the help already in advance :)

**Comment by dereklieu** [comment]
It's really weird that she's seeing a 409 error, as Prose is simply loading what's on the branch at any given point and doesn't maintain a local version of the repo. However, Prose will try to keep drafts and changes in localstorage until you save that particular file, even if you navigate away from the file. Maybe that's causing an issue?

@kaplas perhaps you can try [clearing your session storage and local storage](https://stackoverflow.com/questions/6084099/how-to-view-delete-local-storage-in-firefox) of the offending articles.

**Comment by kaplas** [comment]
@dereklieu Nope, both local storage and session storage are empty. I just checked this from Chrome developer tools.

[Commit history from GitHub](https://github.com/niinapiira/neppari.net/commits/gh-pages) shows that `281fbe` is the latest commit that has gone through to GitHub. So that raises a question of where is that `9bfe9f`even coming from...

**Comment by kaplas** [comment]
OK. I `git pull`'d the repository, made a test commit, and pushed it to GitHub. Now all the commits (problematic `9bfe9f`, test commit from command line, as well as a new edit commit from Prose) are all showing up on the [GitHub commit history](https://github.com/niinapiira/neppari.net/commits/gh-pages). And everything works once again.

@dereklieu Sorry for the distraction; I just really thought that Prose has some kind of a git clone of its own, and it would have somehow caused this problem. I'll close this issue now.

## For future reference, if you have this same problem

1. Clone the repository in question locally
2. Make a new test commit
3. Push changes to the GitHub remote
4. Check that you can see the commits on the GitHub website, and ensure that editing at Prose works once again
5. Wonder why the heck this happened on the GitHub side

**Comment by kaplas** [comment]
@dereklieu And thanx for the help anyway :)
