### ISSUE TITLE
Cannot read property '1' of null

### ISSUE THREAD

**Issue by willmedtrainingsolutionscom** [prose/prose#983]
I am doing:

 * Login at prose.io with GitHub credentials
 * Choose branch

Then I see the loading project page indefinitely (I waited several minutes)

![screen](https://cloud.githubusercontent.com/assets/382183/16428717/252144b4-3d41-11e6-8926-033d54dd5dc7.gif)

This happens consistently every time I try. Please let me know how to provide more information that would be helpful.

Also, please unblock my other account, *fulldecent*. I will not again send follow ups to all old issues on this project.

**Comment by dereklieu** [comment]
This is concerning, but I'm unable to recreate the issue. What's your browser/OS? Does it happen throughout, or only in private repos?

I'll contact support to unblock your account.

**Comment by willmedtrainingsolutionscom** [comment]
Thank you. I am Mac 10.11 / Chrome 51.0.2704.103. This is a private repo. It is maybe 500MB in `.git`. Here is the complete _config.yml:
[YML.txt.zip](https://github.com/prose/prose/files/337896/YML.txt.zip)

**Comment by dereklieu** [comment]
That yml file doesn't raise any errors for me when I plug it into a test repo, I don't think it's the problem.

Do you get this loading error if you open prose and visit a different repo, ie [http://prose.io/#prose/prose](http://prose.io/#prose/prose)?

**Comment by fulldecent** [comment]
I get no errors accessing http://prose.io/#prose/prose

**Comment by fulldecent** [comment]
@dereklieu I have invited you to our private repo at https://github.com/fulldecent/mtssites 

The branch that is causing the crash is acls.net

**Comment by dereklieu** [comment]
@fulldecent [this regex](https://github.com/prose/prose/blob/master/app/util.js#L29) is throwing the error because it expects a file with an extension [here](https://github.com/fulldecent/mtssites/blob/acls.net/cpr-2/about/Icon%0D) and doesn't find one.

**Comment by fulldecent** [comment]
Wow, that was fast!

I am not understanding why it is expecting an extension in:

    var matches = path.match(/(.*)\/(.*)$/);

Also, I would have expected something like this:

    var matches = path.match(/^(.*)\/([^\/]*)$/);

**Comment by fulldecent** [comment]
Thanks for looking into this!

**Comment by dereklieu** [comment]
I think I was a little hasty, it's throwing at that line but now not sure why.

**Comment by dereklieu** [comment]
@fulldecent oh it wasn't anything to do with extensions, for some reason there's a carriage return at the end of that file. Compare:

https://github.com/fulldecent/mtssites/blob/acls.net/cpr-2/about/Icon
https://github.com/fulldecent/mtssites/blob/acls.net/cpr-2/about/Icon%0D

If you get rid of that then it should work.

**Comment by fulldecent** [comment]
Deleted that file and confirmed that I can now use Prose. Thank you!
