### ISSUE TITLE
Add include to whitelist editable files

### ISSUE THREAD

**Issue by lsolesen** [prose/prose#984]
It would be great to have some sort of whitelist instead of the blacklist provided by `ignore`. Often I may only have one or two directories which should be editable using prose.io.

**Comment by dereklieu** [comment]
In that case I think you'd want to set a `rooturl` in `_config.yml` to [specify which directory your prose-editable files live in](https://github.com/prose/prose/wiki/Prose-Configuration#options). It might take a bit of adjusting your directory structure if you have two directories instead of one.

**Comment by dereklieu** [comment]
Closing as wont-fix.
