### ISSUE TITLE
Prose no longer loads non-personal repositories, github is giving 404

### ISSUE THREAD

**Issue by andrew-luminal** [prose/prose#985]
Up until very recently (last day or so), prose loaded repositories from organizations you're a part of just fine. Now prose cannot load them and the github endpoint that prose is trying to hit (https://api.github.com/repos/[org]/[repo]) gives a 404. Personal repositories still work. Anybody experiencing this/know what's going on?

**Comment by dereklieu** [comment]
@andrew-luminal confirm that you're logged in?

**Comment by andrew-luminal** [comment]
My bad, this was an internal org issue -- we turned on required third-party at the org level but that wasn't communicated to the whole team. Sorry to pollute this thread!

**Comment by dereklieu** [comment]
No problem, thanks for using Prose!
