### ISSUE TITLE
Generated commit messages should use present tense

### ISSUE THREAD

**Issue by nickmccurdy** [prose/prose#996]
When editing a file in Prose, the commit message starts with something like "Updated", "Created", or "Deleted". However, [it is recommended to use present tense in commit messages](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html), and git itself follows this when generating commits (such as merge commits). I think commit history would look more consistent if Prose used present tense to start commit messages.

**Comment by dereklieu** [comment]
👍 Happy to accept a PR on this.

**Comment by janpio** [comment]
I created a PR for this, updated the content of the language key and also renamed them so that it matches.

I assume the translations itself will be fixed via transifex.
I am not clear if I should also manually update the key names of all the translations!?
